//! Cantrip (level 0) spell definitions.

use super::types::*;
use crate::rules::DamageType;
use crate::world::Ability;
use std::collections::HashMap;

/// Register all cantrips into the spell database.
pub fn register_cantrips(db: &mut HashMap<String, SpellData>) {
    db.insert("fire bolt".to_string(), SpellData {
        name: "Fire Bolt".to_string(),
        level: 0,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You hurl a mote of fire at a creature or object within range. Make a ranged spell attack. On a hit, the target takes 1d10 fire damage. A flammable object hit by this spell ignites if it isn't being worn or carried.".to_string(),
        damage_dice: Some("1d10".to_string()),
        damage_type: Some(DamageType::Fire),
        damage_scaling: DamageScaling::CantripScaling,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: Some(SpellAttackType::Ranged),
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("eldritch blast".to_string(), SpellData {
        name: "Eldritch Blast".to_string(),
        level: 0,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "A beam of crackling energy streaks toward a creature within range. Make a ranged spell attack. On a hit, the target takes 1d10 force damage. The spell creates more beams at higher levels: two beams at 5th level, three at 11th, and four at 17th.".to_string(),
        damage_dice: Some("1d10".to_string()),
        damage_type: Some(DamageType::Force),
        damage_scaling: DamageScaling::CantripScaling,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: Some(SpellAttackType::Ranged),
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Warlock],
    });

    db.insert("sacred flame".to_string(), SpellData {
        name: "Sacred Flame".to_string(),
        level: 0,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "Flame-like radiance descends on a creature that you can see within range. The target must succeed on a Dexterity saving throw or take 1d8 radiant damage. The target gains no benefit from cover for this saving throw.".to_string(),
        damage_dice: Some("1d8".to_string()),
        damage_type: Some(DamageType::Radiant),
        damage_scaling: DamageScaling::CantripScaling,
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("no damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric],
    });

    db.insert("ray of frost".to_string(), SpellData {
        name: "Ray of Frost".to_string(),
        level: 0,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "A frigid beam of blue-white light streaks toward a creature within range. Make a ranged spell attack. On a hit, it takes 1d8 cold damage, and its speed is reduced by 10 feet until the start of your next turn.".to_string(),
        damage_dice: Some("1d8".to_string()),
        damage_type: Some(DamageType::Cold),
        damage_scaling: DamageScaling::CantripScaling,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: Some(SpellAttackType::Ranged),
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("chill touch".to_string(), SpellData {
        name: "Chill Touch".to_string(),
        level: 0,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vs(),
        duration: SpellDuration::Rounds(1),
        concentration: false,
        ritual: false,
        description: "You create a ghostly, skeletal hand in the space of a creature within range. Make a ranged spell attack. On a hit, the target takes 1d8 necrotic damage, and it can't regain hit points until the start of your next turn. If you hit an undead target, it also has disadvantage on attack rolls against you until the end of your next turn.".to_string(),
        damage_dice: Some("1d8".to_string()),
        damage_type: Some(DamageType::Necrotic),
        damage_scaling: DamageScaling::CantripScaling,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: Some(SpellAttackType::Ranged),
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("light".to_string(), SpellData {
        name: "Light".to_string(),
        level: 0,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("a firefly or phosphorescent moss"),
        duration: SpellDuration::Hours(1),
        concentration: false,
        ritual: false,
        description: "You touch one object that is no larger than 10 feet in any dimension. Until the spell ends, the object sheds bright light in a 20-foot radius and dim light for an additional 20 feet.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("mage hand".to_string(), SpellData {
        name: "Mage Hand".to_string(),
        level: 0,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: false,
        ritual: false,
        description: "A spectral, floating hand appears at a point you choose within range. The hand can manipulate objects, open doors, stow or retrieve items, or pour out contents. It can't attack, activate magic items, or carry more than 10 pounds.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("prestidigitation".to_string(), SpellData {
        name: "Prestidigitation".to_string(),
        level: 0,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(10),
        components: Components::vs(),
        duration: SpellDuration::Hours(1),
        concentration: false,
        ritual: false,
        description: "This spell is a minor magical trick that novice spellcasters use for practice. You create one of several minor effects: sensory effect, light/snuff candle, clean/soil object, chill/warm/flavor material, make symbol or mark, create trinket or illusory image.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("acid splash".to_string(), SpellData {
        name: "Acid Splash".to_string(),
        level: 0,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You hurl a bubble of acid. Choose one creature within range, or choose two creatures within range that are within 5 feet of each other. A target must succeed on a Dexterity saving throw or take 1d6 acid damage.".to_string(),
        damage_dice: Some("1d6".to_string()),
        damage_type: Some(DamageType::Acid),
        damage_scaling: DamageScaling::CantripScaling,
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("no damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("blade ward".to_string(), SpellData {
        name: "Blade Ward".to_string(),
        level: 0,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vs(),
        duration: SpellDuration::Rounds(1),
        concentration: false,
        ritual: false,
        description: "You extend your hand and trace a sigil of warding in the air. Until the end of your next turn, you have resistance against bludgeoning, piercing, and slashing damage dealt by weapon attacks.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("dancing lights".to_string(), SpellData {
        name: "Dancing Lights".to_string(),
        level: 0,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vsm("a bit of phosphorus or wychwood, or a glowworm"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "You create up to four torch-sized lights within range, making them appear as torches, lanterns, or glowing orbs that hover in the air for the duration. You can combine the four lights into one glowing vaguely humanoid form of Medium size. Each light sheds dim light in a 10-foot radius.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("druidcraft".to_string(), SpellData {
        name: "Druidcraft".to_string(),
        level: 0,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "Whispering to the spirits of nature, you create one of several minor effects: predict weather for 24 hours, make a flower blossom or seed pod open or leaf bud bloom, create a harmless sensory effect, or instantly light or snuff out a candle, torch, or small campfire.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Druid],
    });

    db.insert("guidance".to_string(), SpellData {
        name: "Guidance".to_string(),
        level: 0,
        school: SpellSchool::Divination,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check. The spell then ends.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Druid],
    });

    db.insert("mending".to_string(), SpellData {
        name: "Mending".to_string(),
        level: 0,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Minutes(1),
        range: SpellRange::Touch,
        components: Components::vsm("two lodestones"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "This spell repairs a single break or tear in an object you touch, such as a broken chain link, two halves of a broken key, a torn cloak, or a leaking wineskin. As long as the break or tear is no larger than 1 foot in any dimension, you mend it, leaving no trace of the former damage.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Druid, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("message".to_string(), SpellData {
        name: "Message".to_string(),
        level: 0,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vsm("a short piece of copper wire"),
        duration: SpellDuration::Rounds(1),
        concentration: false,
        ritual: false,
        description: "You point your finger toward a creature within range and whisper a message. The target (and only the target) hears the message and can reply in a whisper that only you can hear. You can cast this spell through solid objects if you are familiar with the target and know it is beyond the barrier.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("mind sliver".to_string(), SpellData {
        name: "Mind Sliver".to_string(),
        level: 0,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::v(),
        duration: SpellDuration::Rounds(1),
        concentration: false,
        ritual: false,
        description: "You drive a disorienting spike of psychic energy into the mind of one creature you can see within range. The target must succeed on an Intelligence saving throw or take 1d6 psychic damage and subtract 1d4 from the next saving throw it makes before the end of your next turn.".to_string(),
        damage_dice: Some("1d6".to_string()),
        damage_type: Some(DamageType::Psychic),
        damage_scaling: DamageScaling::CantripScaling,
        healing_dice: None,
        save_type: Some(Ability::Intelligence),
        save_effect: Some("no damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("minor illusion".to_string(), SpellData {
        name: "Minor Illusion".to_string(),
        level: 0,
        school: SpellSchool::Illusion,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::sm("a bit of fleece"),
        duration: SpellDuration::Minutes(1),
        concentration: false,
        ritual: false,
        description: "You create a sound or an image of an object within range that lasts for the duration. The illusion also ends if you dismiss it as an action or cast this spell again. If you create a sound, its volume can range from a whisper to a scream. If you create an image, it must fit within a 5-foot cube and cannot create light, sound, smell, or any other sensory effect.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("poison spray".to_string(), SpellData {
        name: "Poison Spray".to_string(),
        level: 0,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(10),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You extend your hand toward a creature you can see within range and project a puff of noxious gas from your palm. The creature must succeed on a Constitution saving throw or take 1d12 poison damage.".to_string(),
        damage_dice: Some("1d12".to_string()),
        damage_type: Some(DamageType::Poison),
        damage_scaling: DamageScaling::CantripScaling,
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("no damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Druid, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("produce flame".to_string(), SpellData {
        name: "Produce Flame".to_string(),
        level: 0,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vs(),
        duration: SpellDuration::Minutes(10),
        concentration: false,
        ritual: false,
        description: "A flickering flame appears in your hand. The flame remains there for the duration and harms neither you nor your equipment. The flame sheds bright light in a 10-foot radius and dim light for an additional 10 feet. You can also attack with the flame, hurling it at a creature within 30 feet. Make a ranged spell attack. On a hit, the target takes 1d8 fire damage. The spell ends when you hurl the flame.".to_string(),
        damage_dice: Some("1d8".to_string()),
        damage_type: Some(DamageType::Fire),
        damage_scaling: DamageScaling::CantripScaling,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: Some(SpellAttackType::Ranged),
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Druid],
    });

    db.insert("resistance".to_string(), SpellData {
        name: "Resistance".to_string(),
        level: 0,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("a miniature cloak"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one saving throw of its choice. It can roll the die before or after making the saving throw. The spell then ends.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Druid],
    });

    db.insert("shocking grasp".to_string(), SpellData {
        name: "Shocking Grasp".to_string(),
        level: 0,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "Lightning springs from your hand to deliver a shock to a creature you try to touch. Make a melee spell attack against the target. You have advantage on the attack roll if the target is wearing armor made of metal. On a hit, the target takes 1d8 lightning damage, and it can't take reactions until the start of its next turn.".to_string(),
        damage_dice: Some("1d8".to_string()),
        damage_type: Some(DamageType::Lightning),
        damage_scaling: DamageScaling::CantripScaling,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: Some(SpellAttackType::Melee),
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("shillelagh".to_string(), SpellData {
        name: "Shillelagh".to_string(),
        level: 0,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::BonusAction,
        range: SpellRange::Touch,
        components: Components::vsm("mistletoe, a shamrock leaf, and a club or quarterstaff"),
        duration: SpellDuration::Minutes(1),
        concentration: false,
        ritual: false,
        description: "The wood of a club or quarterstaff you are holding is imbued with nature's power. For the duration, you can use your spellcasting ability instead of Strength for the attack and damage rolls of melee attacks using that weapon, and the weapon's damage die becomes a d8. The weapon also becomes magical, if it isn't already.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Druid],
    });

    db.insert("spare the dying".to_string(), SpellData {
        name: "Spare the Dying".to_string(),
        level: 0,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You touch a living creature that has 0 hit points. The creature becomes stable. This spell has no effect on undead or constructs.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric],
    });

    db.insert("thaumaturgy".to_string(), SpellData {
        name: "Thaumaturgy".to_string(),
        level: 0,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::v(),
        duration: SpellDuration::Minutes(1),
        concentration: false,
        ritual: false,
        description: "You manifest a minor wonder, a sign of supernatural power. You create one of these effects: your voice booms up to three times as loud, you cause flames to flicker/brighten/dim/change color, you cause harmless tremors, you create an instantaneous sound, you cause an unlocked door or window to fly open or slam shut, or you alter the appearance of your eyes for 1 minute.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric],
    });

    db.insert("thorn whip".to_string(), SpellData {
        name: "Thorn Whip".to_string(),
        level: 0,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vsm("the stem of a plant with thorns"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You create a long, vine-like whip covered in thorns that lashes out at your command toward a creature in range. Make a melee spell attack against the target. If the attack hits, the creature takes 1d6 piercing damage, and if the creature is Large or smaller, you pull the creature up to 10 feet closer to you.".to_string(),
        damage_dice: Some("1d6".to_string()),
        damage_type: Some(DamageType::Piercing),
        damage_scaling: DamageScaling::CantripScaling,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: Some(SpellAttackType::Melee),
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Druid],
    });

    db.insert("thunderclap".to_string(), SpellData {
        name: "Thunderclap".to_string(),
        level: 0,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(5),
        components: Components::s(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You create a burst of thunderous sound that can be heard up to 100 feet away. Each creature within range, other than you, must succeed on a Constitution saving throw or take 1d6 thunder damage.".to_string(),
        damage_dice: Some("1d6".to_string()),
        damage_type: Some(DamageType::Thunder),
        damage_scaling: DamageScaling::CantripScaling,
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("no damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Druid, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("toll the dead".to_string(), SpellData {
        name: "Toll the Dead".to_string(),
        level: 0,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You point at one creature you can see within range, and the sound of a dolorous bell fills the air around it for a moment. The target must succeed on a Wisdom saving throw or take 1d8 necrotic damage. If the target is missing any of its hit points, it instead takes 1d12 necrotic damage.".to_string(),
        damage_dice: Some("1d8".to_string()),
        damage_type: Some(DamageType::Necrotic),
        damage_scaling: DamageScaling::CantripScaling,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("no damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("true strike".to_string(), SpellData {
        name: "True Strike".to_string(),
        level: 0,
        school: SpellSchool::Divination,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::s(),
        duration: SpellDuration::Rounds(1),
        concentration: true,
        ritual: false,
        description: "You extend your hand and point a finger at a target in range. Your magic grants you a brief insight into the target's defenses. On your next turn, you gain advantage on your first attack roll against the target, provided that this spell hasn't ended.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("vicious mockery".to_string(), SpellData {
        name: "Vicious Mockery".to_string(),
        level: 0,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::v(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You unleash a string of insults laced with subtle enchantments at a creature you can see within range. If the target can hear you (though it need not understand you), it must succeed on a Wisdom saving throw or take 1d4 psychic damage and have disadvantage on the next attack roll it makes before the end of its next turn.".to_string(),
        damage_dice: Some("1d4".to_string()),
        damage_type: Some(DamageType::Psychic),
        damage_scaling: DamageScaling::CantripScaling,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("no damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard],
    });

    db.insert("word of radiance".to_string(), SpellData {
        name: "Word of Radiance".to_string(),
        level: 0,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(5),
        components: Components::vsm("a holy symbol"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You utter a divine word, and burning radiance erupts from you. Each creature of your choice that you can see within range must succeed on a Constitution saving throw or take 1d6 radiant damage.".to_string(),
        damage_dice: Some("1d6".to_string()),
        damage_type: Some(DamageType::Radiant),
        damage_scaling: DamageScaling::CantripScaling,
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("no damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric],
    });
}
