//! 2nd level spell definitions.

use super::types::*;
use crate::rules::DamageType;
use crate::world::Ability;
use std::collections::HashMap;

/// Register all 2nd level spells into the spell database.
pub fn register_level2(db: &mut HashMap<String, SpellData>) {
    db.insert("scorching ray".to_string(), SpellData {
        name: "Scorching Ray".to_string(),
        level: 2,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You create three rays of fire and hurl them at targets within range. You can hurl them at one target or several. Make a ranged spell attack for each ray. On a hit, the target takes 2d6 fire damage. When cast with a higher level slot, you create one additional ray per slot level above 2nd.".to_string(),
        damage_dice: Some("2d6".to_string()), // Per ray
        damage_type: Some(DamageType::Fire),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "2d6".to_string() }, // Additional ray
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: Some(SpellAttackType::Ranged),
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("hold person".to_string(), SpellData {
        name: "Hold Person".to_string(),
        level: 2,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vsm("a small, straight piece of iron"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "Choose a humanoid that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration. At the end of each of its turns, the target can make another Wisdom saving throw. On a success, the spell ends on the target.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("not paralyzed".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Druid, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("misty step".to_string(), SpellData {
        name: "Misty Step".to_string(),
        level: 2,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::BonusAction,
        range: SpellRange::Self_,
        components: Components::v(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("spiritual weapon".to_string(), SpellData {
        name: "Spiritual Weapon".to_string(),
        level: 2,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::BonusAction,
        range: SpellRange::Feet(60),
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: false,
        ritual: false,
        description: "You create a floating, spectral weapon within range that lasts for the duration. When you cast the spell, you can make a melee spell attack against a creature within 5 feet of the weapon. On a hit, the target takes 1d8 + your spellcasting ability modifier force damage. As a bonus action on your turn, you can move the weapon up to 20 feet and repeat the attack.".to_string(),
        damage_dice: Some("1d8".to_string()),
        damage_type: Some(DamageType::Force),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d8".to_string() }, // Per 2 slot levels
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: Some(SpellAttackType::Melee),
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric],
    });

    db.insert("aid".to_string(), SpellData {
        name: "Aid".to_string(),
        level: 2,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vsm("a tiny strip of white cloth"),
        duration: SpellDuration::Hours(8),
        concentration: false,
        ritual: false,
        description: "Your spell bolsters your allies with toughness and resolve. Choose up to three creatures within range. Each target's hit point maximum and current hit points increase by 5 for the duration. At Higher Levels: When you cast this spell using a spell slot of 3rd level or higher, a target's hit points increase by an additional 5 for each slot level above 2nd.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Paladin],
    });

    db.insert("alter self".to_string(), SpellData {
        name: "Alter Self".to_string(),
        level: 2,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vs(),
        duration: SpellDuration::Hours(1),
        concentration: true,
        ritual: false,
        description: "You assume a different form. When you cast the spell, choose one of the following options: Aquatic Adaptation (gain swimming speed and water breathing), Change Appearance (alter your appearance), or Natural Weapons (grow claws, fangs, or other natural weapons that deal 1d6 + Strength modifier bludgeoning, piercing, or slashing damage and are magical).".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("arcane lock".to_string(), SpellData {
        name: "Arcane Lock".to_string(),
        level: 2,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("gold dust worth at least 25 gp, which the spell consumes"),
        duration: SpellDuration::UntilDispelled,
        concentration: false,
        ritual: false,
        description: "You touch a closed door, window, gate, chest, or other entryway, and it becomes locked for the duration. You and the creatures you designate when you cast this spell can open the object normally. You can also set a password that, when spoken within 5 feet of the object, suppresses this spell for 1 minute. Otherwise, it is impassable until it is broken or the spell is dispelled or suppressed.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Wizard],
    });

    db.insert("barkskin".to_string(), SpellData {
        name: "Barkskin".to_string(),
        level: 2,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("a handful of oak bark"),
        duration: SpellDuration::Hours(1),
        concentration: true,
        ritual: false,
        description: "You touch a willing creature. Until the spell ends, the target's skin has a rough, bark-like appearance, and the target's AC can't be less than 16, regardless of what kind of armor it is wearing.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Druid, SpellClass::Ranger],
    });

    db.insert("blindness/deafness".to_string(), SpellData {
        name: "Blindness/Deafness".to_string(),
        level: 2,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::v(),
        duration: SpellDuration::Minutes(1),
        concentration: false,
        ritual: false,
        description: "You can blind or deafen a foe. Choose one creature that you can see within range to make a Constitution saving throw. If it fails, the target is either blinded or deafened (your choice) for the duration. At the end of each of its turns, the target can make a Constitution saving throw. On a success, the spell ends. At Higher Levels: When you cast this spell using a spell slot of 3rd level or higher, you can target one additional creature for each slot level above 2nd.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("not blinded/deafened".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("blur".to_string(), SpellData {
        name: "Blur".to_string(),
        level: 2,
        school: SpellSchool::Illusion,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::v(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "Your body becomes blurred, shifting and wavering to all who can see you. For the duration, any creature has disadvantage on attack rolls against you. An attacker is immune to this effect if it doesn't rely on sight, as with blindsight, or can see through illusions, as with truesight.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("cloud of daggers".to_string(), SpellData {
        name: "Cloud of Daggers".to_string(),
        level: 2,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vsm("a sliver of glass"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "You fill the air with spinning daggers in a cube 5 feet on each side, centered on a point you choose within range. A creature takes 4d4 slashing damage when it enters the spell's area for the first time on a turn or starts its turn there. At Higher Levels: When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 2d4 for each slot level above 2nd.".to_string(),
        damage_dice: Some("4d4".to_string()),
        damage_type: Some(DamageType::Slashing),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "2d4".to_string() },
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Cube(5),
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("crown of madness".to_string(), SpellData {
        name: "Crown of Madness".to_string(),
        level: 2,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "One humanoid of your choice that you can see within range must succeed on a Wisdom saving throw or become charmed by you for the duration. While the target is charmed in this way, a twisted crown of jagged iron appears on its head, and a madness glows in its eyes. The charmed target must use its action before moving on each of its turns to make a melee attack against a creature other than itself that you mentally choose.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("not charmed".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("darkness".to_string(), SpellData {
        name: "Darkness".to_string(),
        level: 2,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vsm("bat fur and a drop of pitch or piece of coal"),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "Magical darkness spreads from a point you choose within range to fill a 15-foot-radius sphere for the duration. The darkness spreads around corners. A creature with darkvision can't see through this darkness, and nonmagical light can't illuminate it. If the point you choose is on an object you are holding or one that isn't being worn or carried, the darkness emanates from the object and moves with it. Completely covering the source of the darkness with an opaque object blocks the darkness.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(15),
        classes: vec![SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("darkvision".to_string(), SpellData {
        name: "Darkvision".to_string(),
        level: 2,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("either a pinch of dried carrot or an agate"),
        duration: SpellDuration::Hours(8),
        concentration: false,
        ritual: false,
        description: "You touch a willing creature to grant it the ability to see in the dark. For the duration, that creature has darkvision out to a range of 60 feet.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Druid, SpellClass::Ranger, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("detect thoughts".to_string(), SpellData {
        name: "Detect Thoughts".to_string(),
        level: 2,
        school: SpellSchool::Divination,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vsm("a copper piece"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "For the duration, you can read the thoughts of certain creatures. When you cast the spell and as your action on each turn until the spell ends, you can focus your mind on any one creature that you can see within 30 feet of you. If the creature you choose has an Intelligence of 3 or lower or doesn't speak any language, the creature is unaffected. You initially learn the surface thoughts of the creature. As an action, you can probe deeper into its mind. The target must make a Wisdom saving throw. If it fails, you gain insight into its reasoning.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("resists deeper probing".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("enhance ability".to_string(), SpellData {
        name: "Enhance Ability".to_string(),
        level: 2,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("fur or a feather from a beast"),
        duration: SpellDuration::Hours(1),
        concentration: true,
        ritual: false,
        description: "You touch a creature and bestow upon it a magical enhancement. Choose one of the following effects; the target gains that effect until the spell ends. Bear's Endurance: advantage on Constitution checks and 2d6 temporary hit points. Bull's Strength: advantage on Strength checks and doubled carrying capacity. Cat's Grace: advantage on Dexterity checks and no fall damage from 20 feet or less. Eagle's Splendor: advantage on Charisma checks. Fox's Cunning: advantage on Intelligence checks. Owl's Wisdom: advantage on Wisdom checks. At Higher Levels: you can target one additional creature for each slot level above 2nd.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Druid, SpellClass::Sorcerer],
    });

    db.insert("enlarge/reduce".to_string(), SpellData {
        name: "Enlarge/Reduce".to_string(),
        level: 2,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vsm("a pinch of powdered iron"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "You cause a creature or an object you can see within range to grow larger or smaller for the duration. Choose either a creature or an object that is neither worn nor carried. If the target is unwilling, it can make a Constitution saving throw. On a success, the spell has no effect. Enlarge: The target's size doubles in all dimensions, and its weight is multiplied by eight. This growth increases its size by one category. The target also has advantage on Strength checks and Strength saving throws. The target's weapons also grow; while enlarged, the target's weapons deal 1d4 extra damage. Reduce: The target's size is halved in all dimensions, and its weight is reduced to one-eighth of normal. The target has disadvantage on Strength checks and Strength saving throws. The target's weapons also shrink; while reduced, the target's weapons deal 1d4 less damage.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("spell has no effect".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("find steed".to_string(), SpellData {
        name: "Find Steed".to_string(),
        level: 2,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Minutes(10),
        range: SpellRange::Feet(30),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You summon a spirit that assumes the form of an unusually intelligent, strong, and loyal steed, creating a long-lasting bond with it. Appearing in an unoccupied space within range, the steed takes on a form that you choose: a warhorse, a pony, a camel, an elk, or a mastiff. The steed has the statistics of the chosen form, though it is a celestial, fey, or fiend instead of its normal type. While your steed is within 1 mile of you, you can communicate with it telepathically. While mounted on your steed, you can make any spell you cast that targets only you also target your steed.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Paladin],
    });

    db.insert("flame blade".to_string(), SpellData {
        name: "Flame Blade".to_string(),
        level: 2,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::BonusAction,
        range: SpellRange::Self_,
        components: Components::vsm("leaf of sumac"),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "You evoke a fiery blade in your free hand. The blade is similar in size and shape to a scimitar, and it lasts for the duration. If you let go of the blade, it disappears, but you can evoke the blade again as a bonus action. You can use your action to make a melee spell attack with the fiery blade. On a hit, the target takes 3d6 fire damage. The flaming blade sheds bright light in a 10-foot radius and dim light for an additional 10 feet. At Higher Levels: the damage increases by 1d6 for every two slot levels above 2nd.".to_string(),
        damage_dice: Some("3d6".to_string()),
        damage_type: Some(DamageType::Fire),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d6".to_string() },
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: Some(SpellAttackType::Melee),
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Druid],
    });

    db.insert("flaming sphere".to_string(), SpellData {
        name: "Flaming Sphere".to_string(),
        level: 2,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vsm("a bit of tallow, a pinch of brimstone, and a dusting of powdered iron"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "A 5-foot-diameter sphere of fire appears in an unoccupied space of your choice within range and lasts for the duration. Any creature that ends its turn within 5 feet of the sphere must make a Dexterity saving throw. The creature takes 2d6 fire damage on a failed save, or half as much damage on a successful one. As a bonus action, you can move the sphere up to 30 feet. If you ram the sphere into a creature, that creature must make the saving throw against the sphere's damage, and the sphere stops moving this turn. At Higher Levels: the damage increases by 1d6 for each slot level above 2nd.".to_string(),
        damage_dice: Some("2d6".to_string()),
        damage_type: Some(DamageType::Fire),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d6".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(5),
        classes: vec![SpellClass::Druid, SpellClass::Wizard],
    });

    db.insert("gentle repose".to_string(), SpellData {
        name: "Gentle Repose".to_string(),
        level: 2,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("a pinch of salt and one copper piece placed on each of the corpse's eyes, which must remain there for the duration"),
        duration: SpellDuration::Days(10),
        concentration: false,
        ritual: true,
        description: "You touch a corpse or other remains. For the duration, the target is protected from decay and can't become undead. The spell also effectively extends the time limit on raising the target from the dead, since days spent under the influence of this spell don't count against the time limit of spells such as raise dead.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Wizard],
    });

    db.insert("heat metal".to_string(), SpellData {
        name: "Heat Metal".to_string(),
        level: 2,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vsm("a piece of iron and a flame"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "Choose a manufactured metal object, such as a metal weapon or a suit of heavy or medium metal armor, that you can see within range. You cause the object to glow red-hot. Any creature in physical contact with the object takes 2d8 fire damage when you cast the spell. Until the spell ends, you can use a bonus action on each of your subsequent turns to cause this damage again. If a creature is holding or wearing the object and takes the damage from it, the creature must succeed on a Constitution saving throw or drop the object if it can. If it doesn't drop the object, it has disadvantage on attack rolls and ability checks until the start of your next turn. At Higher Levels: the damage increases by 1d8 for each slot level above 2nd.".to_string(),
        damage_dice: Some("2d8".to_string()),
        damage_type: Some(DamageType::Fire),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d8".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("doesn't drop object but has disadvantage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Druid],
    });

    db.insert("invisibility".to_string(), SpellData {
        name: "Invisibility".to_string(),
        level: 2,
        school: SpellSchool::Illusion,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("an eyelash encased in gum arabic"),
        duration: SpellDuration::Hours(1),
        concentration: true,
        ritual: false,
        description: "A creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it is on the target's person. The spell ends for a target that attacks or casts a spell. At Higher Levels: When you cast this spell using a spell slot of 3rd level or higher, you can target one additional creature for each slot level above 2nd.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("knock".to_string(), SpellData {
        name: "Knock".to_string(),
        level: 2,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::v(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "Choose an object that you can see within range. The object can be a door, a box, a chest, a set of manacles, a padlock, or another object that contains a mundane or magical means that prevents access. A target that is held shut by a mundane lock or that is stuck or barred becomes unlocked, unstuck, or unbarred. If the object has multiple locks, only one of them is unlocked. If you choose a target that is held shut with arcane lock, that spell is suppressed for 10 minutes, during which time the target can be opened and shut normally. When you cast the spell, a loud knock, audible from as far away as 300 feet, emanates from the target object.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("lesser restoration".to_string(), SpellData {
        name: "Lesser Restoration".to_string(),
        level: 2,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You touch a creature and can end either one disease or one condition afflicting it. The condition can be blinded, deafened, paralyzed, or poisoned.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Druid, SpellClass::Paladin, SpellClass::Ranger],
    });

    db.insert("levitate".to_string(), SpellData {
        name: "Levitate".to_string(),
        level: 2,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vsm("either a small leather loop or a piece of golden wire bent into a cup shape with a long shank on one end"),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "One creature or loose object of your choice that you can see within range rises vertically, up to 20 feet, and remains suspended there for the duration. The spell can levitate a target that weighs up to 500 pounds. An unwilling creature that succeeds on a Constitution saving throw is unaffected. The target can move only by pushing or pulling against a fixed object or surface within reach (such as a wall or a ceiling), which allows it to move as if it were climbing. You can change the target's altitude by up to 20 feet in either direction on your turn.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("unaffected".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("locate animals or plants".to_string(), SpellData {
        name: "Locate Animals or Plants".to_string(),
        level: 2,
        school: SpellSchool::Divination,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vsm("a bit of fur from a bloodhound"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: true,
        description: "Describe or name a specific kind of beast or plant. Concentrating on the voice of nature in your surroundings, you learn the direction and distance to the closest creature or plant of that kind within 5 miles, if any are present.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Druid, SpellClass::Ranger],
    });

    db.insert("locate object".to_string(), SpellData {
        name: "Locate Object".to_string(),
        level: 2,
        school: SpellSchool::Divination,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vsm("a forked twig"),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "Describe or name an object that is familiar to you. You sense the direction to the object's location, as long as that object is within 1,000 feet of you. If the object is in motion, you know the direction of its movement. The spell can locate a specific object known to you, as long as you have seen it up close within 30 feet at least once. Alternatively, the spell can locate the nearest object of a particular kind. This spell can't locate an object if any thickness of lead blocks a direct path between you and the object.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Druid, SpellClass::Paladin, SpellClass::Ranger, SpellClass::Wizard],
    });

    db.insert("magic mouth".to_string(), SpellData {
        name: "Magic Mouth".to_string(),
        level: 2,
        school: SpellSchool::Illusion,
        casting_time: CastingTime::Minutes(1),
        range: SpellRange::Feet(30),
        components: Components::vsm("a small bit of honeycomb and jade dust worth at least 10 gp, which the spell consumes"),
        duration: SpellDuration::UntilDispelled,
        concentration: false,
        ritual: true,
        description: "You implant a message within an object in range, a message that is uttered when a trigger condition is met. Choose an object that you can see and that isn't being worn or carried by another creature. Then speak the message, which must be 25 words or less, though it can be delivered over as long as 10 minutes. Finally, determine the circumstance that will trigger the spell to deliver your message. When that circumstance occurs, a magical mouth appears on the object and recites the message in your voice and at the same volume you spoke.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Wizard],
    });

    db.insert("magic weapon".to_string(), SpellData {
        name: "Magic Weapon".to_string(),
        level: 2,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::BonusAction,
        range: SpellRange::Touch,
        components: Components::vs(),
        duration: SpellDuration::Hours(1),
        concentration: true,
        ritual: false,
        description: "You touch a nonmagical weapon. Until the spell ends, that weapon becomes a magic weapon with a +1 bonus to attack rolls and damage rolls. At Higher Levels: When you cast this spell using a spell slot of 4th level or higher, the bonus increases to +2. When you use a spell slot of 6th level or higher, the bonus increases to +3.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Paladin, SpellClass::Wizard],
    });

    db.insert("melf's acid arrow".to_string(), SpellData {
        name: "Melf's Acid Arrow".to_string(),
        level: 2,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(90),
        components: Components::vsm("powdered rhubarb leaf and an adder's stomach"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "A shimmering green arrow streaks toward a target within range and bursts in a spray of acid. Make a ranged spell attack against the target. On a hit, the target takes 4d4 acid damage immediately and 2d4 acid damage at the end of its next turn. On a miss, the arrow splashes the target with acid for half as much of the initial damage and no damage at the end of its next turn. At Higher Levels: the damage (both initial and later) increases by 1d4 for each slot level above 2nd.".to_string(),
        damage_dice: Some("4d4".to_string()),
        damage_type: Some(DamageType::Acid),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d4".to_string() },
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: Some(SpellAttackType::Ranged),
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Wizard],
    });

    db.insert("mirror image".to_string(), SpellData {
        name: "Mirror Image".to_string(),
        level: 2,
        school: SpellSchool::Illusion,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: false,
        ritual: false,
        description: "Three illusory duplicates of yourself appear in your space. Until the spell ends, the duplicates move with you and mimic your actions, shifting position so it's impossible to track which image is real. You can use your action to dismiss the illusory duplicates. Each time a creature targets you with an attack during the spell's duration, roll a d20 to determine whether the attack instead targets one of your duplicates. If you have three duplicates, you must roll a 6 or higher to change the attack's target to a duplicate. With two duplicates, you must roll an 8 or higher. With one duplicate, you must roll an 11 or higher. A duplicate's AC equals 10 + your Dexterity modifier. If an attack hits a duplicate, the duplicate is destroyed.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("moonbeam".to_string(), SpellData {
        name: "Moonbeam".to_string(),
        level: 2,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vsm("several seeds of any moonseed plant and a piece of opalescent feldspar"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "A silvery beam of pale light shines down in a 5-foot-radius, 40-foot-high cylinder centered on a point within range. Until the spell ends, dim light fills the cylinder. When a creature enters the spell's area for the first time on a turn or starts its turn there, it is engulfed in ghostly flames that cause searing pain, and it must make a Constitution saving throw. It takes 2d10 radiant damage on a failed save, or half as much damage on a successful one. A shapechanger makes its saving throw with disadvantage. If it fails, it also instantly reverts to its original form and can't assume a different form until it leaves the spell's light. On each of your turns after you cast this spell, you can use an action to move the beam up to 60 feet in any direction. At Higher Levels: the damage increases by 1d10 for each slot level above 2nd.".to_string(),
        damage_dice: Some("2d10".to_string()),
        damage_type: Some(DamageType::Radiant),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d10".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Cylinder(5, 40),
        classes: vec![SpellClass::Druid],
    });

    db.insert("pass without trace".to_string(), SpellData {
        name: "Pass without Trace".to_string(),
        level: 2,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vsm("ashes from a burned leaf of mistletoe and a sprig of spruce"),
        duration: SpellDuration::Hours(1),
        concentration: true,
        ritual: false,
        description: "A veil of shadows and silence radiates from you, masking you and your companions from detection. For the duration, each creature you choose within 30 feet of you (including you) has a +10 bonus to Dexterity (Stealth) checks and can't be tracked except by magical means. A creature that receives this bonus leaves behind no tracks or other traces of its passage.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(30),
        classes: vec![SpellClass::Druid, SpellClass::Ranger],
    });

    db.insert("protection from poison".to_string(), SpellData {
        name: "Protection from Poison".to_string(),
        level: 2,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vs(),
        duration: SpellDuration::Hours(1),
        concentration: false,
        ritual: false,
        description: "You touch a creature. If it is poisoned, you neutralize the poison. If more than one poison afflicts the target, you neutralize one poison that you know is present, or you neutralize one at random. For the duration, the target has advantage on saving throws against being poisoned, and it has resistance to poison damage.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Druid, SpellClass::Paladin, SpellClass::Ranger],
    });

    db.insert("ray of enfeeblement".to_string(), SpellData {
        name: "Ray of Enfeeblement".to_string(),
        level: 2,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "A black beam of enervating energy springs from your finger toward a creature within range. Make a ranged spell attack against the target. On a hit, the target deals only half damage with weapon attacks that use Strength until the spell ends. At the end of each of the target's turns, it can make a Constitution saving throw against the spell. On a success, the spell ends.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("spell ends".to_string()),
        attack_type: Some(SpellAttackType::Ranged),
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("rope trick".to_string(), SpellData {
        name: "Rope Trick".to_string(),
        level: 2,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("powdered corn extract and a twisted loop of parchment"),
        duration: SpellDuration::Hours(1),
        concentration: false,
        ritual: false,
        description: "You touch a length of rope that is up to 60 feet long. One end of the rope then rises into the air until the whole rope hangs perpendicular to the ground. At the upper end of the rope, an invisible entrance opens to an extradimensional space that lasts until the spell ends. The extradimensional space can be reached by climbing to the top of the rope. The space can hold as many as eight Medium or smaller creatures. The rope can be pulled into the space, making the rope disappear from view outside the space. Attacks and spells can't cross through the entrance into or out of the extradimensional space, but those inside can see out of it as if through a 3-foot-by-5-foot window centered on the rope. Anything inside the extradimensional space drops out when the spell ends.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Wizard],
    });

    db.insert("see invisibility".to_string(), SpellData {
        name: "See Invisibility".to_string(),
        level: 2,
        school: SpellSchool::Divination,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vsm("a pinch of talc and a small sprinkling of powdered silver"),
        duration: SpellDuration::Hours(1),
        concentration: false,
        ritual: false,
        description: "For the duration, you see invisible creatures and objects as if they were visible, and you can see into the Ethereal Plane. Ethereal creatures and objects appear ghostly and translucent.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("shatter".to_string(), SpellData {
        name: "Shatter".to_string(),
        level: 2,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vsm("a chip of mica"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "A sudden loud ringing noise, painfully intense, erupts from a point of your choice within range. Each creature in a 10-foot-radius sphere centered on that point must make a Constitution saving throw. A creature takes 3d8 thunder damage on a failed save, or half as much damage on a successful one. A creature made of inorganic material such as stone, crystal, or metal has disadvantage on this saving throw. A nonmagical object that isn't being worn or carried also takes the damage if it's in the spell's area. At Higher Levels: the damage increases by 1d8 for each slot level above 2nd.".to_string(),
        damage_dice: Some("3d8".to_string()),
        damage_type: Some(DamageType::Thunder),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d8".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(10),
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("silence".to_string(), SpellData {
        name: "Silence".to_string(),
        level: 2,
        school: SpellSchool::Illusion,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vs(),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: true,
        description: "For the duration, no sound can be created within or pass through a 20-foot-radius sphere centered on a point you choose within range. Any creature or object entirely inside the sphere is immune to thunder damage, and creatures are deafened while entirely inside it. Casting a spell that includes a verbal component is impossible there.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(20),
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Ranger],
    });

    db.insert("spider climb".to_string(), SpellData {
        name: "Spider Climb".to_string(),
        level: 2,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("a drop of bitumen and a spider"),
        duration: SpellDuration::Hours(1),
        concentration: true,
        ritual: false,
        description: "Until the spell ends, one willing creature you touch gains the ability to move up, down, and across vertical surfaces and upside down along ceilings, while leaving its hands free. The target also gains a climbing speed equal to its walking speed.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("spike growth".to_string(), SpellData {
        name: "Spike Growth".to_string(),
        level: 2,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(150),
        components: Components::vsm("seven sharp thorns or seven small twigs, each sharpened to a point"),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "The ground in a 20-foot radius centered on a point within range twists and sprouts hard spikes and thorns. The area becomes difficult terrain for the duration. When a creature moves into or within the area, it takes 2d4 piercing damage for every 5 feet it travels. The transformation of the ground is camouflaged to look natural. Any creature that can't see the area at the time the spell is cast must make a Wisdom (Perception) check against your spell save DC to recognize the terrain as hazardous before entering it.".to_string(),
        damage_dice: Some("2d4".to_string()),
        damage_type: Some(DamageType::Piercing),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(20),
        classes: vec![SpellClass::Druid, SpellClass::Ranger],
    });

    db.insert("suggestion".to_string(), SpellData {
        name: "Suggestion".to_string(),
        level: 2,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vsm("a snake's tongue and either a bit of honeycomb or a drop of sweet oil"),
        duration: SpellDuration::Hours(8),
        concentration: true,
        ritual: false,
        description: "You suggest a course of activity (limited to a sentence or two) and magically influence a creature you can see within range that can hear and understand you. Creatures that can't be charmed are immune to this effect. The suggestion must be worded in such a manner as to make the course of action sound reasonable. Asking the creature to stab itself, throw itself onto a spear, immolate itself, or do some other obviously harmful act ends the spell. The target must make a Wisdom saving throw. On a failed save, it pursues the course of action you described to the best of its ability. The suggested course of action can continue for the entire duration.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("not affected".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("warding bond".to_string(), SpellData {
        name: "Warding Bond".to_string(),
        level: 2,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("a pair of platinum rings worth at least 50 gp each, which you and the target must wear for the duration"),
        duration: SpellDuration::Hours(1),
        concentration: false,
        ritual: false,
        description: "This spell wards a willing creature you touch and creates a mystic connection between you and the target until the spell ends. While the target is within 60 feet of you, it gains a +1 bonus to AC and saving throws, and it has resistance to all damage. Also, each time it takes damage, you take the same amount of damage. The spell ends if you drop to 0 hit points or if you and the target become separated by more than 60 feet. It also ends if the spell is cast again on either of the connected creatures.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric],
    });

    db.insert("web".to_string(), SpellData {
        name: "Web".to_string(),
        level: 2,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vsm("a bit of spiderweb"),
        duration: SpellDuration::Hours(1),
        concentration: true,
        ritual: false,
        description: "You conjure a mass of thick, sticky webbing at a point of your choice within range. The webs fill a 20-foot cube from that point for the duration. The webs are difficult terrain and lightly obscure their area. If the webs aren't anchored between two solid masses (such as walls or trees) or layered across a floor, wall, or ceiling, the conjured web collapses on itself, and the spell ends at the start of your next turn. A creature that starts its turn in the webs or that enters them during its turn must make a Dexterity saving throw. On a failed save, the creature is restrained as long as it remains in the webs or until it breaks free. A creature restrained by the webs can use its action to make a Strength check against your spell save DC. If it succeeds, it is no longer restrained. The webs are flammable.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("not restrained".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Cube(20),
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("zone of truth".to_string(), SpellData {
        name: "Zone of Truth".to_string(),
        level: 2,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vs(),
        duration: SpellDuration::Minutes(10),
        concentration: false,
        ritual: false,
        description: "You create a magical zone that guards against deception in a 15-foot-radius sphere centered on a point of your choice within range. Until the spell ends, a creature that enters the spell's area for the first time on a turn or starts its turn there must make a Charisma saving throw. On a failed save, a creature can't speak a deliberate lie while in the radius. You know whether each creature succeeds or fails on its saving throw. An affected creature is aware of the spell and can thus avoid answering questions to which it would normally respond with a lie. Such a creature can be evasive in its answers as long as it remains within the boundaries of the truth.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Charisma),
        save_effect: Some("can speak lies".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(15),
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Paladin],
    });
}
