//! 6th level spell definitions.

use super::types::*;
use crate::rules::DamageType;
use crate::world::Ability;
use std::collections::HashMap;

/// Register all 6th level spells into the spell database.
pub fn register_level6(db: &mut HashMap<String, SpellData>) {
    db.insert("chain lightning".to_string(), SpellData {
        name: "Chain Lightning".to_string(),
        level: 6,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(150),
        components: Components::vsm("a bit of fur; a piece of amber, glass, or a crystal rod; and three silver pins"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You create a bolt of lightning that arcs toward a target of your choice that you can see within range. Three bolts then leap from that target to as many as three other targets, each of which must be within 30 feet of the first target. A target can be a creature or an object and can be targeted by only one of the bolts. A target must make a Dexterity saving throw, taking 10d8 lightning damage on a failed save, or half as much on a successful one.".to_string(),
        damage_dice: Some("10d8".to_string()),
        damage_type: Some(DamageType::Lightning),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d8".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("disintegrate".to_string(), SpellData {
        name: "Disintegrate".to_string(),
        level: 6,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vsm("a lodite and a pinch of dust"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "A thin green ray springs from your pointing finger to a target that you can see within range. The target can be a creature, an object, or a creation of magical force. A creature targeted by this spell must make a Dexterity saving throw. On a failed save, the target takes 10d6 + 40 force damage. If this damage reduces the target to 0 hit points, it is disintegrated. A disintegrated creature and everything it is wearing and carrying are reduced to a pile of fine gray dust.".to_string(),
        damage_dice: Some("10d6+40".to_string()),
        damage_type: Some(DamageType::Force),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "3d6".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("no damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("globe of invulnerability".to_string(), SpellData {
        name: "Globe of Invulnerability".to_string(),
        level: 6,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::SelfRadius(10),
        components: Components::vsm("a glass or crystal bead that shatters when the spell ends"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "An immobile, faintly shimmering barrier springs into existence in a 10-foot radius around you and remains for the duration. Any spell of 5th level or lower cast from outside the barrier can't affect creatures or objects within it, even if the spell is cast using a higher level spell slot. Such a spell can target creatures and objects within the barrier, but the spell has no effect on them.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(10),
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("harm".to_string(), SpellData {
        name: "Harm".to_string(),
        level: 6,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You unleash a virulent disease on a creature that you can see within range. The target must make a Constitution saving throw. On a failed save, it takes 14d6 necrotic damage, or half as much damage on a successful save. The damage can't reduce the target's hit points below 1. If the target fails the saving throw, its hit point maximum is reduced for 1 hour by an amount equal to the necrotic damage it took.".to_string(),
        damage_dice: Some("14d6".to_string()),
        damage_type: Some(DamageType::Necrotic),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric],
    });

    db.insert("heal".to_string(), SpellData {
        name: "Heal".to_string(),
        level: 6,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "Choose a creature that you can see within range. A surge of positive energy washes through the creature, causing it to regain 70 hit points. This spell also ends blindness, deafness, and any diseases affecting the target. This spell has no effect on constructs or undead.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "10".to_string() },
        healing_dice: Some("70".to_string()),
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Druid],
    });

    db.insert("mass suggestion".to_string(), SpellData {
        name: "Mass Suggestion".to_string(),
        level: 6,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vsm("a snake's tongue and either a bit of honeycomb or a drop of sweet oil"),
        duration: SpellDuration::Hours(24),
        concentration: false,
        ritual: false,
        description: "You suggest a course of activity (limited to a sentence or two) and magically influence up to twelve creatures of your choice that you can see within range and that can hear and understand you. The suggestion must be worded in such a manner as to make the course of action sound reasonable. Each target must make a Wisdom saving throw. On a failed save, it pursues the course of action you described.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("not affected".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("sunbeam".to_string(), SpellData {
        name: "Sunbeam".to_string(),
        level: 6,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::SelfLine(60, 5),
        components: Components::vsm("a magnifying glass"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "A beam of brilliant light flashes out from your hand in a 5-foot-wide, 60-foot-long line. Each creature in the line must make a Constitution saving throw. On a failed save, a creature takes 6d8 radiant damage and is blinded until your next turn. On a successful save, it takes half as much damage and isn't blinded. Undead and oozes have disadvantage on this saving throw.".to_string(),
        damage_dice: Some("6d8".to_string()),
        damage_type: Some(DamageType::Radiant),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("half damage, not blinded".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Line(60, 5),
        classes: vec![SpellClass::Cleric, SpellClass::Druid, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("arcane gate".to_string(), SpellData {
        name: "Arcane Gate".to_string(),
        level: 6,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(500),
        components: Components::vs(),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "You create linked teleportation portals that remain open for the duration. Choose two points on the ground that you can see, one point within 10 feet of you and one point within 500 feet of you. A circular portal, 10 feet in diameter, opens over each point. If the portal would open in the space occupied by a creature, the spell fails. The portals are two-dimensional glowing rings filled with mist, hovering inches from the ground and perpendicular to it. A ring is visible only from one side, which you choose. Any creature or object entering the portal exits from the other portal as if the two were adjacent.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("blade barrier".to_string(), SpellData {
        name: "Blade Barrier".to_string(),
        level: 6,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(90),
        components: Components::vs(),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "You create a vertical wall of whirling, razor-sharp blades made of magical energy. The wall appears within range and lasts for the duration. You can make a straight wall up to 100 feet long, 20 feet high, and 5 feet thick, or a ringed wall up to 60 feet in diameter, 20 feet high, and 5 feet thick. The wall provides three-quarters cover to creatures behind it, and its space is difficult terrain. When a creature enters the wall's area for the first time on a turn or starts its turn there, the creature must make a Dexterity saving throw, taking 6d10 slashing damage on a failed save, or half as much on a successful one.".to_string(),
        damage_dice: Some("6d10".to_string()),
        damage_type: Some(DamageType::Slashing),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric],
    });

    db.insert("circle of death".to_string(), SpellData {
        name: "Circle of Death".to_string(),
        level: 6,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(150),
        components: Components::vsm("the powder of a crushed black pearl worth at least 500 gp"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "A sphere of negative energy ripples out in a 60-foot-radius sphere from a point within range. Each creature in that area must make a Constitution saving throw. A target takes 8d6 necrotic damage on a failed save, or half as much damage on a successful one.".to_string(),
        damage_dice: Some("8d6".to_string()),
        damage_type: Some(DamageType::Necrotic),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "2d6".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(60),
        classes: vec![SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("conjure fey".to_string(), SpellData {
        name: "Conjure Fey".to_string(),
        level: 6,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Minutes(1),
        range: SpellRange::Feet(90),
        components: Components::vs(),
        duration: SpellDuration::Hours(1),
        concentration: true,
        ritual: false,
        description: "You summon a fey creature of challenge rating 6 or lower, or a fey spirit that takes the form of a beast of challenge rating 6 or lower. It appears in an unoccupied space that you can see within range. The fey creature disappears when it drops to 0 hit points or when the spell ends. The fey creature is friendly to you and your companions for the duration. It obeys any verbal commands that you issue to it, as long as they don't violate its alignment. If you don't issue any commands, the creature defends itself but otherwise takes no actions.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Druid, SpellClass::Warlock],
    });

    db.insert("create undead".to_string(), SpellData {
        name: "Create Undead".to_string(),
        level: 6,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Minutes(1),
        range: SpellRange::Feet(10),
        components: Components::vsm("one clay pot filled with grave dirt, one clay pot filled with brackish water, and one 150 gp black onyx stone for each corpse"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You can cast this spell only at night. Choose up to three corpses of Medium or Small humanoids within range. Each corpse becomes a ghoul under your control. As a bonus action on each of your turns, you can mentally command any creature you made with this spell if the creature is within 120 feet of you. You decide what action the creature will take and where it will move during its next turn. At higher levels, you can create more powerful undead.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("drawmij's instant summons".to_string(), SpellData {
        name: "Drawmij's Instant Summons".to_string(),
        level: 6,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Minutes(1),
        range: SpellRange::Touch,
        components: Components::vsm("a sapphire worth 1,000 gp"),
        duration: SpellDuration::UntilDispelled,
        concentration: false,
        ritual: true,
        description: "You touch an object weighing 10 pounds or less whose longest dimension is 6 feet or less. The spell leaves an invisible mark on its surface and invisibly inscribes the name of the item on the sapphire you use as the material component. Each time you cast this spell, you must use a different sapphire. At any time thereafter, you can use your action to speak the item's name and crush the sapphire. The item instantly appears in your hand regardless of physical or planar distances.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Wizard],
    });

    db.insert("eyebite".to_string(), SpellData {
        name: "Eyebite".to_string(),
        level: 6,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "For the spell's duration, your eyes become an inky void imbued with dread power. One creature of your choice within 60 feet of you that you can see must succeed on a Wisdom saving throw or be affected by one of the following effects of your choice: Asleep, Panicked, or Sickened. On each of your turns until the spell ends, you can use your action to target another creature but can't target a creature that has already succeeded on a saving throw against this casting of eyebite.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("not affected".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("find the path".to_string(), SpellData {
        name: "Find the Path".to_string(),
        level: 6,
        school: SpellSchool::Divination,
        casting_time: CastingTime::Minutes(1),
        range: SpellRange::Self_,
        components: Components::vsm("a set of divinatory tools--such as bones, ivory sticks, cards, teeth, or carved runes--worth 100 gp and an object from the location you wish to find"),
        duration: SpellDuration::Days(1),
        concentration: true,
        ritual: false,
        description: "This spell allows you to find the shortest, most direct physical route to a specific fixed location that you are familiar with on the same plane of existence. If you name a destination on another plane of existence, a destination that moves, or a destination that isn't specific, the spell fails. For the duration, as long as you are on the same plane of existence as the destination, you know how far it is and in what direction it lies. While you are traveling there, whenever you are presented with a choice of paths along the way, you automatically determine which path is the shortest and most direct route.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Druid],
    });

    db.insert("flesh to stone".to_string(), SpellData {
        name: "Flesh to Stone".to_string(),
        level: 6,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vsm("a pinch of lime, water, and earth"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "You attempt to turn one creature that you can see within range into stone. If the target's body is made of flesh, the creature must make a Constitution saving throw. On a failed save, it is restrained as its flesh begins to harden. On a successful save, the creature isn't affected. A creature restrained by this spell must make another Constitution saving throw at the end of each of its turns. If it successfully saves against this spell three times, the spell ends. If it fails its saves three times, it is turned to stone and subjected to the petrified condition for the duration.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("not affected".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("forbiddance".to_string(), SpellData {
        name: "Forbiddance".to_string(),
        level: 6,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Minutes(10),
        range: SpellRange::Touch,
        components: Components::vsm("a sprinkling of holy water, rare incense, and powdered ruby worth at least 1,000 gp"),
        duration: SpellDuration::Days(1),
        concentration: false,
        ritual: true,
        description: "You create a ward against magical travel that protects up to 40,000 square feet of floor space to a height of 30 feet above the floor. For the duration, creatures can't teleport into the area or use portals to enter the area. The spell proofs the area against planar travel. Additionally, the spell damages types of creatures that you choose when you cast it. Choose one or more of the following: celestials, elementals, fey, fiends, and undead. When a chosen creature enters the spell's area for the first time on a turn or starts its turn there, the creature takes 5d10 radiant or necrotic damage.".to_string(),
        damage_dice: Some("5d10".to_string()),
        damage_type: Some(DamageType::Radiant),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric],
    });

    db.insert("guards and wards".to_string(), SpellData {
        name: "Guards and Wards".to_string(),
        level: 6,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Minutes(10),
        range: SpellRange::Touch,
        components: Components::vsm("burning incense, a small measure of brimstone and oil, a knotted string, a small amount of umber hulk blood, and a small silver rod worth at least 10 gp"),
        duration: SpellDuration::Hours(24),
        concentration: false,
        ritual: false,
        description: "You create a ward that protects up to 2,500 square feet of floor space. The warded area can be up to 20 feet tall and shaped as you desire. You can ward several stories of a stronghold by dividing the area among them. When you cast this spell, you can specify individuals that are unaffected by any or all of the effects that you choose. You can also specify a password that, when spoken aloud, makes the speaker immune to these effects. The spell creates the following effects within the warded area: corridors filled with fog, doors locked, stairs filled with webs, and other effects.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Wizard],
    });

    db.insert("heroes' feast".to_string(), SpellData {
        name: "Heroes' Feast".to_string(),
        level: 6,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Minutes(10),
        range: SpellRange::Feet(30),
        components: Components::vsm("a gem-encrusted bowl worth at least 1,000 gp, which the spell consumes"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You bring forth a great feast, including magnificent food and drink. The feast takes 1 hour to consume and disappears at the end of that time, and the beneficial effects don't set in until this hour is over. Up to twelve creatures can partake of the feast. A creature that partakes of the feast gains several benefits: cured of all diseases and poison, becomes immune to poison and being frightened, and makes all Wisdom saving throws with advantage. Its hit point maximum also increases by 2d10, and it gains the same number of hit points. These benefits last for 24 hours.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: Some("2d10".to_string()),
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Druid],
    });

    db.insert("magic jar".to_string(), SpellData {
        name: "Magic Jar".to_string(),
        level: 6,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Minutes(1),
        range: SpellRange::Self_,
        components: Components::vsm("a gem, crystal, reliquary, or some other ornamental container worth at least 500 gp"),
        duration: SpellDuration::UntilDispelled,
        concentration: false,
        ritual: false,
        description: "Your body falls into a catatonic state as your soul leaves it and enters the container you used for the spell's material component. While your soul inhabits the container, you are aware of your surroundings as if you were in the container's space. You can't move or use reactions. The only action you can take is to project your soul up to 100 feet out of the container, either returning to your living body or attempting to possess a humanoid's body. You can attempt to possess any humanoid within 100 feet of you that you can see. The target must make a Charisma saving throw. On a failure, your soul moves into the target's body.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Charisma),
        save_effect: Some("not possessed".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Wizard],
    });

    db.insert("move earth".to_string(), SpellData {
        name: "Move Earth".to_string(),
        level: 6,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vsm("an iron blade and a small bag containing a mixture of soils--clay, loam, and sand"),
        duration: SpellDuration::Hours(2),
        concentration: true,
        ritual: false,
        description: "Choose an area of terrain no larger than 40 feet on a side within range. You can reshape dirt, sand, or clay in the area in any manner you choose for the duration. You can raise or lower the area's elevation, create or fill in a trench, erect or flatten a wall, or form a pillar. The extent of any such changes can't exceed half the area's largest dimension. It takes 10 minutes for these changes to complete. At the end of every 10 minutes you spend concentrating on the spell, you can choose a new area of terrain to affect.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Druid, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("otiluke's freezing sphere".to_string(), SpellData {
        name: "Otiluke's Freezing Sphere".to_string(),
        level: 6,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(300),
        components: Components::vsm("a small crystal sphere"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "A frigid globe of cold energy streaks from your fingertips to a point of your choice within range, where it explodes in a 60-foot-radius sphere. Each creature within the area must make a Constitution saving throw. On a failed save, a creature takes 10d6 cold damage. On a successful save, it takes half as much damage. If the globe strikes a body of water or a liquid that is principally water, it freezes the liquid to a depth of 6 inches over an area 30 feet square.".to_string(),
        damage_dice: Some("10d6".to_string()),
        damage_type: Some(DamageType::Cold),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d6".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(60),
        classes: vec![SpellClass::Wizard],
    });

    db.insert("otto's irresistible dance".to_string(), SpellData {
        name: "Otto's Irresistible Dance".to_string(),
        level: 6,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "Choose one creature that you can see within range. The target begins a comic dance in place: shuffling, tapping its feet, and capering for the duration. Creatures that can't be charmed are immune to this spell. A dancing creature must use all its movement to dance without leaving its space and has disadvantage on Dexterity saving throws and attack rolls. While the target is affected by this spell, other creatures have advantage on attack rolls against it. As an action, a dancing creature makes a Wisdom saving throw to regain control of itself. On a successful save, the spell ends.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("spell ends".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Wizard],
    });

    db.insert("planar ally".to_string(), SpellData {
        name: "Planar Ally".to_string(),
        level: 6,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Minutes(10),
        range: SpellRange::Feet(60),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You beseech an otherworldly entity for aid. The being must be known to you: a god, a primordial, a demon prince, or some other being of cosmic power. That entity sends a celestial, an elemental, or a fiend loyal to it to aid you, making the creature appear in an unoccupied space within range. If you know a specific creature's name, you can speak that name when you cast this spell to request that creature. The creature is under no compulsion to behave in any particular way. You can ask the creature to perform a service in exchange for payment.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric],
    });

    db.insert("programmed illusion".to_string(), SpellData {
        name: "Programmed Illusion".to_string(),
        level: 6,
        school: SpellSchool::Illusion,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vsm("a bit of fleece and jade dust worth at least 25 gp"),
        duration: SpellDuration::UntilDispelled,
        concentration: false,
        ritual: false,
        description: "You create an illusion of an object, a creature, or some other visible phenomenon within range that activates when a specific condition occurs. The illusion is imperceptible until then. It must be no larger than a 30-foot cube, and you decide when you cast the spell how the illusion behaves and what sounds it makes. This scripted performance can last up to 5 minutes. When the condition you specify occurs, the illusion springs into existence and performs in the manner you described. Once the illusion finishes performing, it disappears and remains dormant for 10 minutes before it can be activated again.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Cube(30),
        classes: vec![SpellClass::Bard, SpellClass::Wizard],
    });

    db.insert("transport via plants".to_string(), SpellData {
        name: "Transport via Plants".to_string(),
        level: 6,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(10),
        components: Components::vs(),
        duration: SpellDuration::Rounds(1),
        concentration: false,
        ritual: false,
        description: "This spell creates a magical link between a Large or larger inanimate plant within range and another plant, at any distance, on the same plane of existence. You must have seen or touched the destination plant at least once before. For the duration, any creature can step into the target plant and exit from the destination plant by using 5 feet of movement.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Druid],
    });

    db.insert("true seeing".to_string(), SpellData {
        name: "True Seeing".to_string(),
        level: 6,
        school: SpellSchool::Divination,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("an ointment for the eyes that costs 25 gp; is made from mushroom powder, saffron, and fat; and is consumed by the spell"),
        duration: SpellDuration::Hours(1),
        concentration: false,
        ritual: false,
        description: "This spell gives the willing creature you touch the ability to see things as they actually are. For the duration, the creature has truesight, notices secret doors hidden by magic, and can see into the Ethereal Plane, all out to a range of 120 feet.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("wall of ice".to_string(), SpellData {
        name: "Wall of Ice".to_string(),
        level: 6,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vsm("a small piece of quartz"),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "You create a wall of ice on a solid surface within range. You can form it into a hemispherical dome or a sphere with a radius of up to 10 feet, or you can shape a flat surface made up of ten 10-foot-square panels. The wall is 1 foot thick and lasts for the duration. If the wall cuts through a creature's space when it appears, the creature within its area is pushed to one side of the wall and must make a Dexterity saving throw, taking 10d6 cold damage on a failed save, or half as much on a successful one. The wall is an object with AC 12 and can be damaged and breached.".to_string(),
        damage_dice: Some("10d6".to_string()),
        damage_type: Some(DamageType::Cold),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "2d6".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Wizard],
    });

    db.insert("wall of thorns".to_string(), SpellData {
        name: "Wall of Thorns".to_string(),
        level: 6,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vsm("a handful of thorns"),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "You create a wall of tough, pliable, tangled brush bristling with needle-sharp thorns. The wall appears within range on a solid surface and lasts for the duration. You choose to make the wall up to 60 feet long, 10 feet high, and 5 feet thick or a circle that has a 20-foot diameter and is up to 20 feet high and 5 feet thick. The wall blocks line of sight. When the wall appears, each creature within its area must make a Dexterity saving throw. On a failed save, a creature takes 7d8 piercing damage, or half as much on a successful save.".to_string(),
        damage_dice: Some("7d8".to_string()),
        damage_type: Some(DamageType::Piercing),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d8".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Druid],
    });

    db.insert("wind walk".to_string(), SpellData {
        name: "Wind Walk".to_string(),
        level: 6,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Minutes(1),
        range: SpellRange::Feet(30),
        components: Components::vsm("fire and holy water"),
        duration: SpellDuration::Hours(8),
        concentration: false,
        ritual: false,
        description: "You and up to ten willing creatures you can see within range assume a gaseous form for the duration, appearing as wisps of cloud. While in this cloud form, a creature has a flying speed of 300 feet and has resistance to damage from nonmagical weapons. The only actions a creature can take in this form are the Dash action or to revert to its normal form. Reverting takes 1 minute, during which time a creature is incapacitated and can't move.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Druid],
    });

    db.insert("word of recall".to_string(), SpellData {
        name: "Word of Recall".to_string(),
        level: 6,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(5),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You and up to five willing creatures within 5 feet of you instantly teleport to a previously designated sanctuary. You and any creatures that teleport with you appear in the nearest unoccupied space to the spot you designated when you prepared your sanctuary. If you cast this spell without first preparing a sanctuary, the spell has no effect.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric],
    });
}
