//! 5th level spell definitions.

use super::types::*;
use crate::rules::DamageType;
use crate::world::Ability;
use std::collections::HashMap;

/// Register all 5th level spells into the spell database.
pub fn register_level5(db: &mut HashMap<String, SpellData>) {
    db.insert("cloudkill".to_string(), SpellData {
        name: "Cloudkill".to_string(),
        level: 5,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vs(),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "You create a 20-foot-radius sphere of poisonous, yellow-green fog centered on a point you choose within range. The fog spreads around corners and heavily obscures the area. When a creature enters the spell's area for the first time on a turn or starts its turn there, that creature must make a Constitution saving throw. The creature takes 5d8 poison damage on a failed save, or half as much on a successful one.".to_string(),
        damage_dice: Some("5d8".to_string()),
        damage_type: Some(DamageType::Poison),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d8".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(20),
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("cone of cold".to_string(), SpellData {
        name: "Cone of Cold".to_string(),
        level: 5,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::SelfCone(60),
        components: Components::vsm("a small crystal or glass cone"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "A blast of cold air erupts from your hands. Each creature in a 60-foot cone must make a Constitution saving throw. A creature takes 8d8 cold damage on a failed save, or half as much damage on a successful one. A creature killed by this spell becomes a frozen statue until it thaws.".to_string(),
        damage_dice: Some("8d8".to_string()),
        damage_type: Some(DamageType::Cold),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d8".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Cone(60),
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("dominate person".to_string(), SpellData {
        name: "Dominate Person".to_string(),
        level: 5,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "You attempt to beguile a humanoid that you can see within range. It must succeed on a Wisdom saving throw or be charmed by you for the duration. While the target is charmed, you have a telepathic link with it. You can use this telepathic link to issue commands to the creature while you are conscious (no action required), which it does its best to obey.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("not charmed".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("flame strike".to_string(), SpellData {
        name: "Flame Strike".to_string(),
        level: 5,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vsm("a pinch of sulfur"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "A vertical column of divine fire roars down from the heavens in a location you specify. Each creature in a 10-foot-radius, 40-foot-high cylinder centered on a point within range must make a Dexterity saving throw. A creature takes 4d6 fire damage and 4d6 radiant damage on a failed save, or half as much damage on a successful one.".to_string(),
        damage_dice: Some("4d6+4d6".to_string()),
        damage_type: Some(DamageType::Fire),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d6".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Cylinder(10, 40),
        classes: vec![SpellClass::Cleric],
    });

    db.insert("hold monster".to_string(), SpellData {
        name: "Hold Monster".to_string(),
        level: 5,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(90),
        components: Components::vsm("a small, straight piece of iron"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "Choose a creature that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration. This spell has no effect on undead. At the end of each of its turns, the target can make another Wisdom saving throw. On a success, the spell ends on the target.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("not paralyzed".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("mass cure wounds".to_string(), SpellData {
        name: "Mass Cure Wounds".to_string(),
        level: 5,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "A wave of healing energy washes out from a point of your choice within range. Choose up to six creatures in a 30-foot-radius sphere centered on that point. Each target regains hit points equal to 3d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d8".to_string() },
        healing_dice: Some("3d8".to_string()),
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(30),
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Druid],
    });

    db.insert("telekinesis".to_string(), SpellData {
        name: "Telekinesis".to_string(),
        level: 5,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vs(),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "You gain the ability to move or manipulate creatures or objects by thought. When you cast the spell, and as your action each round for the duration, you can exert your will on one creature or object that you can see within range, causing the appropriate effect. You can affect the same target round after round, or choose a new one at any time.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Strength),
        save_effect: Some("resists movement".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("wall of stone".to_string(), SpellData {
        name: "Wall of Stone".to_string(),
        level: 5,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vsm("a small block of granite"),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "A nonmagical wall of solid stone springs into existence at a point you choose within range. The wall is 6 inches thick and is composed of ten 10-foot-by-10-foot panels. Each panel must be contiguous with at least one other panel. If the wall cuts through a creature's space when it appears, the creature is pushed to one side of the wall (your choice).".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Druid, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("animate objects".to_string(), SpellData {
        name: "Animate Objects".to_string(),
        level: 5,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "Objects come to life at your command. Choose up to ten nonmagical objects within range that are not being worn or carried. Medium targets count as two objects, Large targets count as four objects, Huge targets count as eight objects. The objects are friendly to you and your companions. On each of your turns, you can use a bonus action to mentally command any creature you made with this spell.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("antilife shell".to_string(), SpellData {
        name: "Antilife Shell".to_string(),
        level: 5,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vs(),
        duration: SpellDuration::Hours(1),
        concentration: true,
        ritual: false,
        description: "A shimmering barrier extends out from you in a 10-foot radius and moves with you, remaining centered on you and hedging out creatures other than undead and constructs. The barrier lasts for the duration. The barrier prevents an affected creature from passing or reaching through. An affected creature can cast spells or make attacks with ranged or reach weapons through the barrier.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(10),
        classes: vec![SpellClass::Druid],
    });

    db.insert("awaken".to_string(), SpellData {
        name: "Awaken".to_string(),
        level: 5,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Hours(8),
        range: SpellRange::Touch,
        components: Components::vsm("an agate worth at least 1,000 gp, which the spell consumes"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "After spending the casting time tracing magical pathways within a precious gemstone, you touch a Huge or smaller beast or plant. The target must have either no Intelligence score or an Intelligence of 3 or less. The target gains an Intelligence of 10. The target also gains the ability to speak one language you know. If the target is a plant, it gains the ability to move its limbs, roots, vines, creepers, and so forth, and it gains senses similar to a human's. The awakened beast or plant is charmed by you for 30 days or until you or your companions do anything harmful to it.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Druid],
    });

    db.insert("banishing smite".to_string(), SpellData {
        name: "Banishing Smite".to_string(),
        level: 5,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::BonusAction,
        range: SpellRange::Self_,
        components: Components::v(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "The next time you hit a creature with a weapon attack before this spell ends, your weapon crackles with force, and the attack deals an extra 5d10 force damage to the target. Additionally, if this attack reduces the target to 50 hit points or fewer, you banish it. If the target is native to a different plane of existence than the one you're on, the target disappears, returning to its home plane. If the target is native to the plane you're on, the creature vanishes into a harmless demiplane and is incapacitated.".to_string(),
        damage_dice: Some("5d10".to_string()),
        damage_type: Some(DamageType::Force),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Paladin],
    });

    db.insert("bigby's hand".to_string(), SpellData {
        name: "Bigby's Hand".to_string(),
        level: 5,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vsm("an eggshell and a snakeskin glove"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "You create a Large hand of shimmering, translucent force in an unoccupied space that you can see within range. The hand lasts for the spell's duration, and it moves at your command, mimicking the movements of your own hand. The hand is an object that has AC 20 and hit points equal to your hit point maximum. The hand can punch, push, grasp, and interpose itself between you and attacks.".to_string(),
        damage_dice: Some("4d8".to_string()),
        damage_type: Some(DamageType::Force),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "2d8".to_string() },
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: Some(SpellAttackType::Melee),
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("circle of power".to_string(), SpellData {
        name: "Circle of Power".to_string(),
        level: 5,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::v(),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "Divine energy radiates from you, distorting and diffusing magical energy within 30 feet of you. Until the spell ends, the sphere moves with you, centered on you. For the duration, each friendly creature in the area (including you) has advantage on saving throws against spells and other magical effects. Additionally, when an affected creature succeeds on a saving throw made against a spell or magical effect that allows it to make a saving throw to take only half damage, it instead takes no damage.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(30),
        classes: vec![SpellClass::Paladin],
    });

    db.insert("commune".to_string(), SpellData {
        name: "Commune".to_string(),
        level: 5,
        school: SpellSchool::Divination,
        casting_time: CastingTime::Minutes(1),
        range: SpellRange::Self_,
        components: Components::vsm("incense and a vial of holy or unholy water"),
        duration: SpellDuration::Minutes(1),
        concentration: false,
        ritual: true,
        description: "You contact your deity or a divine proxy and ask up to three questions that can be answered with a yes or no. You must ask your questions before the spell ends. You receive a correct answer for each question. Divine beings aren't necessarily omniscient, so you might receive 'unclear' as an answer if a question pertains to information that lies beyond the deity's knowledge.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric],
    });

    db.insert("commune with nature".to_string(), SpellData {
        name: "Commune with Nature".to_string(),
        level: 5,
        school: SpellSchool::Divination,
        casting_time: CastingTime::Minutes(1),
        range: SpellRange::Self_,
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: true,
        description: "You briefly become one with nature and gain knowledge of the surrounding territory. In the outdoors, the spell gives you knowledge of the land within 3 miles of you. In caves and other natural underground settings, the radius is limited to 300 feet. The spell doesn't function where nature has been replaced by construction, such as in dungeons and towns. You instantly gain knowledge of up to three facts of your choice about the terrain, plants, animals, minerals, bodies of water, and so forth.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Druid, SpellClass::Ranger],
    });

    db.insert("conjure elemental".to_string(), SpellData {
        name: "Conjure Elemental".to_string(),
        level: 5,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Minutes(1),
        range: SpellRange::Feet(90),
        components: Components::vsm("burning incense for air, soft clay for earth, sulfur and phosphorus for fire, or water and sand for water"),
        duration: SpellDuration::Hours(1),
        concentration: true,
        ritual: false,
        description: "You call forth an elemental servant. Choose an area of air, earth, fire, or water that fills a 10-foot cube within range. An elemental of challenge rating 5 or lower appropriate to the area you chose appears in an unoccupied space within 10 feet of it. The elemental disappears when it drops to 0 hit points or when the spell ends. The elemental is friendly to you and your companions for the duration. If your concentration is broken, the elemental doesn't disappear but becomes hostile.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Cube(10),
        classes: vec![SpellClass::Druid, SpellClass::Wizard],
    });

    db.insert("conjure volley".to_string(), SpellData {
        name: "Conjure Volley".to_string(),
        level: 5,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(150),
        components: Components::vsm("one piece of ammunition or one thrown weapon"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You fire a piece of nonmagical ammunition from a ranged weapon or throw a nonmagical weapon into the air and choose a point within range. Hundreds of duplicates of the ammunition or weapon fall in a volley from above and then disappear. Each creature in a 40-foot-radius, 20-foot-high cylinder centered on that point must make a Dexterity saving throw. A creature takes 8d8 damage on a failed save, or half as much damage on a successful one. The damage type is the same as that of the ammunition or weapon.".to_string(),
        damage_dice: Some("8d8".to_string()),
        damage_type: Some(DamageType::Piercing),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Cylinder(40, 20),
        classes: vec![SpellClass::Ranger],
    });

    db.insert("contact other plane".to_string(), SpellData {
        name: "Contact Other Plane".to_string(),
        level: 5,
        school: SpellSchool::Divination,
        casting_time: CastingTime::Minutes(1),
        range: SpellRange::Self_,
        components: Components::v(),
        duration: SpellDuration::Minutes(1),
        concentration: false,
        ritual: true,
        description: "You mentally contact a demigod, the spirit of a long-dead sage, or some other mysterious entity from another plane. Contacting this extraplanar intelligence can strain or even break your mind. When you cast this spell, make a DC 15 Intelligence saving throw. On a failure, you take 6d6 psychic damage and are insane until you finish a long rest. While insane, you can't take actions, can't understand what other creatures say, can't read, and speak only in gibberish. On a successful save, you can ask the entity up to five questions.".to_string(),
        damage_dice: Some("6d6".to_string()),
        damage_type: Some(DamageType::Psychic),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Intelligence),
        save_effect: Some("avoids insanity".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("contagion".to_string(), SpellData {
        name: "Contagion".to_string(),
        level: 5,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vs(),
        duration: SpellDuration::Days(7),
        concentration: false,
        ritual: false,
        description: "Your touch inflicts disease. Make a melee spell attack against a creature within your reach. On a hit, the target is poisoned. At the end of each of the poisoned target's turns, the target must make a Constitution saving throw. If the target succeeds on three of these saves, it is no longer poisoned, and the spell ends. If the target fails three of these saves, the target is no longer poisoned, but choose one of the diseases below. The target is subjected to the chosen disease for the spell's duration.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("ends poisoned condition".to_string()),
        attack_type: Some(SpellAttackType::Melee),
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Druid],
    });

    db.insert("creation".to_string(), SpellData {
        name: "Creation".to_string(),
        level: 5,
        school: SpellSchool::Illusion,
        casting_time: CastingTime::Minutes(1),
        range: SpellRange::Feet(30),
        components: Components::vsm("a tiny piece of matter of the same type of the item you plan to create"),
        duration: SpellDuration::Special,
        concentration: false,
        ritual: false,
        description: "You pull wisps of shadow material from the Shadowfell to create a nonliving object of vegetable matter within range: soft goods, rope, wood, or something similar. You can also use this spell to create mineral objects such as stone, crystal, or metal. The object created must be no larger than a 5-foot cube, and the object must be of a form and material that you have seen before. The duration depends on the object's material.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Cube(5),
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("destructive wave".to_string(), SpellData {
        name: "Destructive Wave".to_string(),
        level: 5,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::v(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You strike the ground, creating a burst of divine energy that ripples outward from you. Each creature you choose within 30 feet of you must succeed on a Constitution saving throw or take 5d6 thunder damage, as well as 5d6 radiant or necrotic damage (your choice), and be knocked prone. A creature that succeeds on its saving throw takes half as much damage and isn't knocked prone.".to_string(),
        damage_dice: Some("5d6+5d6".to_string()),
        damage_type: Some(DamageType::Thunder),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("half damage, not prone".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(30),
        classes: vec![SpellClass::Paladin],
    });

    db.insert("dispel evil and good".to_string(), SpellData {
        name: "Dispel Evil and Good".to_string(),
        level: 5,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vsm("holy water or powdered silver and iron"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "Shimmering energy surrounds and protects you from fey, undead, and creatures originating from beyond the Material Plane. For the duration, celestials, elementals, fey, fiends, and undead have disadvantage on attack rolls against you. You can end the spell early by using either of the following special functions: Break Enchantment (touch a charmed, frightened, or possessed creature to end those effects) or Dismissal (make a melee spell attack to banish an extraplanar creature).".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Charisma),
        save_effect: Some("avoids banishment".to_string()),
        attack_type: Some(SpellAttackType::Melee),
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Paladin],
    });

    db.insert("dream".to_string(), SpellData {
        name: "Dream".to_string(),
        level: 5,
        school: SpellSchool::Illusion,
        casting_time: CastingTime::Minutes(1),
        range: SpellRange::Unlimited,
        components: Components::vsm("a handful of sand, a dab of ink, and a writing quill plucked from a sleeping bird"),
        duration: SpellDuration::Hours(8),
        concentration: false,
        ritual: false,
        description: "This spell shapes a creature's dreams. Choose a creature known to you as the target of this spell. The target must be on the same plane of existence as you. You, or a willing creature you touch, enters a trance state, acting as a messenger. While in the trance, the messenger is aware of their surroundings but can't take actions or move. If the target is asleep, the messenger appears in the target's dreams and can converse with the target.".to_string(),
        damage_dice: Some("3d6".to_string()),
        damage_type: Some(DamageType::Psychic),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("avoids nightmare damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("geas".to_string(), SpellData {
        name: "Geas".to_string(),
        level: 5,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Minutes(1),
        range: SpellRange::Feet(60),
        components: Components::v(),
        duration: SpellDuration::Days(30),
        concentration: false,
        ritual: false,
        description: "You place a magical command on a creature that you can see within range, forcing it to carry out some service or refrain from some action or course of activity as you decide. If the creature can understand you, it must succeed on a Wisdom saving throw or become charmed by you for the duration. While the creature is charmed by you, it takes 5d10 psychic damage each time it acts in a manner directly counter to your instructions, but no more than once each day.".to_string(),
        damage_dice: Some("5d10".to_string()),
        damage_type: Some(DamageType::Psychic),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("not charmed".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Druid, SpellClass::Paladin, SpellClass::Wizard],
    });

    db.insert("greater restoration".to_string(), SpellData {
        name: "Greater Restoration".to_string(),
        level: 5,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("diamond dust worth at least 100 gp, which the spell consumes"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You imbue a creature you touch with positive energy to undo a debilitating effect. You can reduce the target's exhaustion level by one, or end one of the following effects on the target: one effect that charmed or petrified the target, one curse (including the target's attunement to a cursed magic item), any reduction to one of the target's ability scores, or one effect reducing the target's hit point maximum.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Druid],
    });

    db.insert("hallow".to_string(), SpellData {
        name: "Hallow".to_string(),
        level: 5,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Hours(24),
        range: SpellRange::Touch,
        components: Components::vsm("herbs, oils, and incense worth at least 1,000 gp, which the spell consumes"),
        duration: SpellDuration::UntilDispelled,
        concentration: false,
        ritual: false,
        description: "You touch a point and infuse an area around it with holy (or unholy) power. The area can have a radius up to 60 feet, and the spell fails if the radius includes an area already under the effect of a hallow spell. The affected area is subject to the following effects: celestials, elementals, fey, fiends, and undead can't enter the area, nor can such creatures charm, frighten, or possess creatures within it. You can also bind an extra effect to the area.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(60),
        classes: vec![SpellClass::Cleric],
    });

    db.insert("insect plague".to_string(), SpellData {
        name: "Insect Plague".to_string(),
        level: 5,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(300),
        components: Components::vsm("a few grains of sugar, some kernels of grain, and a smear of fat"),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "Swarming, biting locusts fill a 20-foot-radius sphere centered on a point you choose within range. The sphere spreads around corners. The sphere remains for the duration, and its area is lightly obscured. The sphere's area is difficult terrain. When the area appears, each creature in it must make a Constitution saving throw. A creature takes 4d10 piercing damage on a failed save, or half as much damage on a successful one. A creature must also make this saving throw when it enters the spell's area for the first time on a turn or ends its turn there.".to_string(),
        damage_dice: Some("4d10".to_string()),
        damage_type: Some(DamageType::Piercing),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d10".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(20),
        classes: vec![SpellClass::Cleric, SpellClass::Druid, SpellClass::Sorcerer],
    });

    db.insert("legend lore".to_string(), SpellData {
        name: "Legend Lore".to_string(),
        level: 5,
        school: SpellSchool::Divination,
        casting_time: CastingTime::Minutes(10),
        range: SpellRange::Self_,
        components: Components::vsm("incense worth at least 250 gp, which the spell consumes, and four ivory strips worth at least 50 gp each"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "Name or describe a person, place, or object. The spell brings to your mind a brief summary of the significant lore about the thing you named. The lore might consist of current tales, forgotten stories, or even secret lore that has never been widely known. If the thing you named isn't of legendary importance, you gain no information. The more information you already have about the thing, the more precise and detailed the information you receive is.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Wizard],
    });

    db.insert("mislead".to_string(), SpellData {
        name: "Mislead".to_string(),
        level: 5,
        school: SpellSchool::Illusion,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::s(),
        duration: SpellDuration::Hours(1),
        concentration: true,
        ritual: false,
        description: "You become invisible at the same time that an illusory double of you appears where you are standing. The double lasts for the duration, but the invisibility ends if you attack or cast a spell. You can use your action to move your illusory double up to twice your speed and make it gesture, speak, and behave in whatever way you choose. You can see through its eyes and hear through its ears as if you were located where it is.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Wizard],
    });

    db.insert("modify memory".to_string(), SpellData {
        name: "Modify Memory".to_string(),
        level: 5,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "You attempt to reshape another creature's memories. One creature that you can see must make a Wisdom saving throw. If you are fighting the creature, it has advantage on the saving throw. On a failed save, the target becomes charmed by you for the duration. While this charm lasts, you can affect the target's memory of an event that it experienced within the last 24 hours and that lasted no more than 10 minutes. You can permanently eliminate all memory of the event, allow the target to recall the event with perfect clarity, change its memory of the details of the event, or create a memory of some other event.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("not charmed".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Wizard],
    });

    db.insert("passwall".to_string(), SpellData {
        name: "Passwall".to_string(),
        level: 5,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vsm("a pinch of sesame seeds"),
        duration: SpellDuration::Hours(1),
        concentration: false,
        ritual: false,
        description: "A passage appears at a point of your choice that you can see on a wooden, plaster, or stone surface (such as a wall, a ceiling, or a floor) within range, and lasts for the duration. You choose the opening's dimensions: up to 5 feet wide, 8 feet tall, and 20 feet deep. The passage creates no instability in a structure surrounding it. When the opening disappears, any creatures or objects still in the passage created by the spell are safely ejected to an unoccupied space nearest to the surface on which you cast the spell.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Wizard],
    });

    db.insert("planar binding".to_string(), SpellData {
        name: "Planar Binding".to_string(),
        level: 5,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Hours(1),
        range: SpellRange::Feet(60),
        components: Components::vsm("a jewel worth at least 1,000 gp, which the spell consumes"),
        duration: SpellDuration::Hours(24),
        concentration: false,
        ritual: false,
        description: "With this spell, you attempt to bind a celestial, an elemental, a fey, or a fiend to your service. The creature must be within range for the entire casting of the spell. At the completion of the casting, the target must make a Charisma saving throw. On a failed save, it is bound to serve you for the duration. If the creature was summoned or created by another spell, that spell's duration is extended to match the duration of this spell. A bound creature must follow your instructions to the best of its ability.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Charisma),
        save_effect: Some("not bound".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Druid, SpellClass::Wizard],
    });

    db.insert("raise dead".to_string(), SpellData {
        name: "Raise Dead".to_string(),
        level: 5,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Hours(1),
        range: SpellRange::Touch,
        components: Components::vsm("a diamond worth at least 500 gp, which the spell consumes"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You return a dead creature you touch to life, provided that it has been dead no longer than 10 days. If the creature's soul is both willing and at liberty to rejoin the body, the creature returns to life with 1 hit point. This spell also neutralizes any poisons and cures nonmagical diseases that affected the creature at the time it died. This spell doesn't remove magical diseases, curses, or similar effects; if these aren't first removed prior to casting the spell, they take effect when the creature returns to life.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Paladin],
    });

    db.insert("scrying".to_string(), SpellData {
        name: "Scrying".to_string(),
        level: 5,
        school: SpellSchool::Divination,
        casting_time: CastingTime::Minutes(10),
        range: SpellRange::Self_,
        components: Components::vsm("a focus worth at least 1,000 gp, such as a crystal ball, a silver mirror, or a font filled with holy water"),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "You can see and hear a particular creature you choose that is on the same plane of existence as you. The target must make a Wisdom saving throw, which is modified by how well you know the target and the sort of physical connection you have to it. If a target knows you're casting this spell, it can fail the saving throw voluntarily if it wants to be observed. On a successful save, the target isn't affected, and you can't use this spell against it again for 24 hours.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("not observed".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Druid, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("seeming".to_string(), SpellData {
        name: "Seeming".to_string(),
        level: 5,
        school: SpellSchool::Illusion,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vs(),
        duration: SpellDuration::Hours(8),
        concentration: false,
        ritual: false,
        description: "This spell allows you to change the appearance of any number of creatures that you can see within range. You give each target you choose a new, illusory appearance. An unwilling target can make a Charisma saving throw, and if it succeeds, it is unaffected by this spell. The spell disguises physical appearance as well as clothing, armor, weapons, and equipment. You can make each creature seem 1 foot shorter or taller and appear thin, fat, or in between.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Charisma),
        save_effect: Some("not disguised".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("swift quiver".to_string(), SpellData {
        name: "Swift Quiver".to_string(),
        level: 5,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::BonusAction,
        range: SpellRange::Touch,
        components: Components::vsm("a quiver containing at least one piece of ammunition"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "You transmute your quiver so it produces an endless supply of nonmagical ammunition, which seems to leap into your hand when you reach for it. On each of your turns until the spell ends, you can use a bonus action to make two attacks with a weapon that uses ammunition from the quiver. Each time you make such a ranged attack, your quiver magically replaces the piece of ammunition you used with a similar piece of nonmagical ammunition.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Ranger],
    });

    db.insert("teleportation circle".to_string(), SpellData {
        name: "Teleportation Circle".to_string(),
        level: 5,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Minutes(1),
        range: SpellRange::Feet(10),
        components: Components::vsm("rare chalks and inks infused with precious gems worth 50 gp, which the spell consumes"),
        duration: SpellDuration::Rounds(1),
        concentration: false,
        ritual: false,
        description: "As you cast the spell, you draw a 10-foot-diameter circle on the ground inscribed with sigils that link your location to a permanent teleportation circle of your choice whose sigil sequence you know and that is on the same plane of existence as you. A shimmering portal opens within the circle you drew and remains open until the end of your next turn. Any creature that enters the portal instantly appears within 5 feet of the destination circle or in the nearest unoccupied space if that space is occupied.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("tree stride".to_string(), SpellData {
        name: "Tree Stride".to_string(),
        level: 5,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "You gain the ability to enter a tree and move from inside it to inside another tree of the same kind within 500 feet. Both trees must be living and at least the same size as you. You must use 5 feet of movement to enter a tree. You instantly know the location of all other trees of the same kind within 500 feet and, as part of the move used to enter the tree, can either pass into one of those trees or step out of the tree you're in.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Druid, SpellClass::Ranger],
    });

    db.insert("wall of force".to_string(), SpellData {
        name: "Wall of Force".to_string(),
        level: 5,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vsm("a pinch of powder made by crushing a clear gemstone"),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "An invisible wall of force springs into existence at a point you choose within range. The wall appears in any orientation you choose, as a horizontal or vertical barrier or at an angle. It can be free floating or resting on a solid surface. You can form it into a hemispherical dome or a sphere with a radius of up to 10 feet, or you can shape a flat surface made up of ten 10-foot-by-10-foot panels. The wall is indestructible and immune to all damage. Nothing can physically pass through the wall.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Wizard],
    });
}
