//! 4th level spell definitions.

use super::types::*;
use crate::rules::DamageType;
use crate::world::Ability;
use std::collections::HashMap;

/// Register all 4th level spells into the spell database.
pub fn register_level4(db: &mut HashMap<String, SpellData>) {
    db.insert("banishment".to_string(), SpellData {
        name: "Banishment".to_string(),
        level: 4,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vsm("an item distasteful to the target"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "You attempt to send one creature that you can see within range to another plane of existence. The target must succeed on a Charisma saving throw or be banished. If the target is native to the plane you're on, it is banished to a harmless demiplane and is incapacitated there. If the spell ends before 1 minute passes, the target reappears. Otherwise, if native to a different plane, it returns there.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Charisma),
        save_effect: Some("not banished".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Paladin, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("blight".to_string(), SpellData {
        name: "Blight".to_string(),
        level: 4,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "Necromantic energy washes over a creature of your choice that you can see within range, draining moisture and vitality from it. The target must make a Constitution saving throw. The target takes 8d8 necrotic damage on a failed save, or half as much damage on a successful one. This spell has no effect on undead or constructs. Plant creatures have disadvantage on the saving throw and take maximum damage.".to_string(),
        damage_dice: Some("8d8".to_string()),
        damage_type: Some(DamageType::Necrotic),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d8".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Druid, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("confusion".to_string(), SpellData {
        name: "Confusion".to_string(),
        level: 4,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(90),
        components: Components::vsm("three nut shells"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "This spell assaults and twists creatures' minds, spawning delusions and provoking uncontrolled action. Each creature in a 10-foot-radius sphere centered on a point you choose must succeed on a Wisdom saving throw or be affected. An affected target can't take reactions and must roll a d10 at the start of each turn to determine its behavior.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("not affected".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(10),
        classes: vec![SpellClass::Bard, SpellClass::Druid, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("dimension door".to_string(), SpellData {
        name: "Dimension Door".to_string(),
        level: 4,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(500),
        components: Components::v(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You teleport yourself from your current location to any other spot within range. You arrive at exactly the spot desired. It can be a place you can see, one you can visualize, or one you can describe by stating distance and direction. You can bring along objects as long as their weight doesn't exceed what you can carry. You can also bring one willing creature of your size or smaller.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("fire shield".to_string(), SpellData {
        name: "Fire Shield".to_string(),
        level: 4,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vsm("a bit of phosphorus or a firefly"),
        duration: SpellDuration::Minutes(10),
        concentration: false,
        ritual: false,
        description: "Thin and wispy flames wreathe your body for the duration, shedding bright light in a 10-foot radius. You can end the spell early. The flames provide a warm shield or chill shield, your choice. The warm shield grants resistance to cold damage, the chill shield grants resistance to fire damage. Whenever a creature within 5 feet of you hits you with a melee attack, the shield erupts with flame. The attacker takes 2d8 fire or cold damage.".to_string(),
        damage_dice: Some("2d8".to_string()),
        damage_type: Some(DamageType::Fire),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Wizard],
    });

    db.insert("greater invisibility".to_string(), SpellData {
        name: "Greater Invisibility".to_string(),
        level: 4,
        school: SpellSchool::Illusion,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "You or a creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it is on the target's person. The invisibility doesn't end early if the target attacks or casts a spell.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("ice storm".to_string(), SpellData {
        name: "Ice Storm".to_string(),
        level: 4,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(300),
        components: Components::vsm("a pinch of dust and a few drops of water"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "A hail of rock-hard ice pounds to the ground in a 20-foot-radius, 40-foot-high cylinder centered on a point within range. Each creature in the cylinder must make a Dexterity saving throw. A creature takes 2d8 bludgeoning damage and 4d6 cold damage on a failed save, or half as much damage on a successful one. Hailstones turn the storm's area of effect into difficult terrain until the end of your next turn.".to_string(),
        damage_dice: Some("2d8+4d6".to_string()),
        damage_type: Some(DamageType::Cold),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d8".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Cylinder(20, 40),
        classes: vec![SpellClass::Druid, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("polymorph".to_string(), SpellData {
        name: "Polymorph".to_string(),
        level: 4,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vsm("a caterpillar cocoon"),
        duration: SpellDuration::Hours(1),
        concentration: true,
        ritual: false,
        description: "This spell transforms a creature that you can see within range into a new form. An unwilling creature must make a Wisdom saving throw to avoid the effect. A shapechanger automatically succeeds. The transformation lasts for the duration, or until the target drops to 0 hit points or dies. The new form can be any beast whose challenge rating is equal to or less than the target's level or CR.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("not transformed".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Druid, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("stoneskin".to_string(), SpellData {
        name: "Stoneskin".to_string(),
        level: 4,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("diamond dust worth 100 gp, which the spell consumes"),
        duration: SpellDuration::Hours(1),
        concentration: true,
        ritual: false,
        description: "This spell turns the flesh of a willing creature you touch as hard as stone. Until the spell ends, the target has resistance to nonmagical bludgeoning, piercing, and slashing damage.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Druid, SpellClass::Ranger, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("wall of fire".to_string(), SpellData {
        name: "Wall of Fire".to_string(),
        level: 4,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vsm("a small piece of phosphorus"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "You create a wall of fire on a solid surface within range. You can make the wall up to 60 feet long, 20 feet high, and 1 foot thick, or a ringed wall up to 20 feet in diameter, 20 feet high, and 1 foot thick. When the wall appears, each creature within its area must make a Dexterity saving throw. On a failed save, a creature takes 5d8 fire damage, or half as much on a successful save.".to_string(),
        damage_dice: Some("5d8".to_string()),
        damage_type: Some(DamageType::Fire),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d8".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Line(60, 20),
        classes: vec![SpellClass::Druid, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("arcane eye".to_string(), SpellData {
        name: "Arcane Eye".to_string(),
        level: 4,
        school: SpellSchool::Divination,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vsm("a bit of bat fur"),
        duration: SpellDuration::Hours(1),
        concentration: true,
        ritual: false,
        description: "You create an invisible, magical eye within range that hovers in the air for the duration. You mentally receive visual information from the eye, which has normal vision and darkvision out to 30 feet. The eye can look in every direction. As an action, you can move the eye up to 30 feet in any direction. The eye can pass through an opening as small as 1 inch in diameter.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Wizard],
    });

    db.insert("aura of life".to_string(), SpellData {
        name: "Aura of Life".to_string(),
        level: 4,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::v(),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "Life-preserving energy radiates from you in an aura with a 30-foot radius. Until the spell ends, the aura moves with you, centered on you. Each nonhostile creature in the aura (including you) has resistance to necrotic damage, and its hit point maximum can't be reduced. In addition, a nonhostile, living creature regains 1 hit point when it starts its turn in the aura with 0 hit points.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(30),
        classes: vec![SpellClass::Paladin],
    });

    db.insert("aura of purity".to_string(), SpellData {
        name: "Aura of Purity".to_string(),
        level: 4,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::v(),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "Purifying energy radiates from you in an aura with a 30-foot radius. Until the spell ends, the aura moves with you, centered on you. Each nonhostile creature in the aura (including you) can't become diseased, has resistance to poison damage, and has advantage on saving throws against effects that cause any of the following conditions: blinded, charmed, deafened, frightened, paralyzed, poisoned, and stunned.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(30),
        classes: vec![SpellClass::Paladin],
    });

    db.insert("charm monster".to_string(), SpellData {
        name: "Charm Monster".to_string(),
        level: 4,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vs(),
        duration: SpellDuration::Hours(1),
        concentration: false,
        ritual: false,
        description: "You attempt to charm a creature you can see within range. It must make a Wisdom saving throw, and it does so with advantage if you or your companions are fighting it. If it fails the saving throw, it is charmed by you until the spell ends or until you or your companions do anything harmful to it. The charmed creature is friendly to you. When the spell ends, the creature knows it was charmed by you.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("not charmed".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Druid, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("compulsion".to_string(), SpellData {
        name: "Compulsion".to_string(),
        level: 4,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "Creatures of your choice that you can see within range and that can hear you must make a Wisdom saving throw. A target automatically succeeds if it can't be charmed. On a failed save, a target is affected by this spell. Until the spell ends, you can use a bonus action on each of your turns to designate a direction. Each affected target must use as much of its movement as possible to move in that direction on its next turn.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("not affected".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard],
    });

    db.insert("conjure minor elementals".to_string(), SpellData {
        name: "Conjure Minor Elementals".to_string(),
        level: 4,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Minutes(1),
        range: SpellRange::Feet(90),
        components: Components::vs(),
        duration: SpellDuration::Hours(1),
        concentration: true,
        ritual: false,
        description: "You summon elementals that appear in unoccupied spaces that you can see within range. Choose one of the following options: one elemental of challenge rating 2 or lower, two elementals of challenge rating 1 or lower, four elementals of challenge rating 1/2 or lower, or eight elementals of challenge rating 1/4 or lower. The summoned creatures are friendly to you and your companions and obey your verbal commands.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Druid, SpellClass::Wizard],
    });

    db.insert("conjure woodland beings".to_string(), SpellData {
        name: "Conjure Woodland Beings".to_string(),
        level: 4,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vsm("one holly berry per creature summoned"),
        duration: SpellDuration::Hours(1),
        concentration: true,
        ritual: false,
        description: "You summon fey creatures that appear in unoccupied spaces that you can see within range. Choose one of the following options: one fey creature of challenge rating 2 or lower, two fey creatures of challenge rating 1 or lower, four fey creatures of challenge rating 1/2 or lower, or eight fey creatures of challenge rating 1/4 or lower. The summoned creatures are friendly to you and your companions and obey your verbal commands.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Druid, SpellClass::Ranger],
    });

    db.insert("control water".to_string(), SpellData {
        name: "Control Water".to_string(),
        level: 4,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(300),
        components: Components::vsm("a drop of water and a pinch of dust"),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "Until the spell ends, you control any freestanding water inside an area you choose that is a cube up to 100 feet on a side. You can choose from any of the following effects when you cast this spell. As an action on your turn, you can repeat the same effect or choose a different one: Flood, Part Water, Redirect Flow, or Whirlpool. Creatures in a whirlpool must make a Strength saving throw or take 2d8 bludgeoning damage and be pulled toward the center.".to_string(),
        damage_dice: Some("2d8".to_string()),
        damage_type: Some(DamageType::Bludgeoning),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Strength),
        save_effect: Some("half damage, not pulled".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Cube(100),
        classes: vec![SpellClass::Cleric, SpellClass::Druid, SpellClass::Wizard],
    });

    db.insert("death ward".to_string(), SpellData {
        name: "Death Ward".to_string(),
        level: 4,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vs(),
        duration: SpellDuration::Hours(8),
        concentration: false,
        ritual: false,
        description: "You touch a creature and grant it a measure of protection from death. The first time the target would drop to 0 hit points as a result of taking damage, the target instead drops to 1 hit point, and the spell ends. If the spell is still in effect when the target is subjected to an effect that would kill it instantaneously without dealing damage, that effect is negated against the target, and the spell ends.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Paladin],
    });

    db.insert("divination".to_string(), SpellData {
        name: "Divination".to_string(),
        level: 4,
        school: SpellSchool::Divination,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vsm("incense and a sacrificial offering appropriate to your religion, together worth at least 25 gp, which the spell consumes"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: true,
        description: "Your magic and an offering put you in contact with a god or a god's servants. You ask a single question concerning a specific goal, event, or activity to occur within 7 days. The DM offers a truthful reply, which might be a short phrase, a cryptic rhyme, or an omen. The spell doesn't account for circumstances that might change the outcome, such as additional spellcasting or the loss of a companion.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric],
    });

    db.insert("dominate beast".to_string(), SpellData {
        name: "Dominate Beast".to_string(),
        level: 4,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "You attempt to beguile a beast that you can see within range. It must succeed on a Wisdom saving throw or be charmed by you for the duration. If you or creatures that are friendly to you are fighting it, it has advantage on the saving throw. While the beast is charmed, you have a telepathic link with it. You can use this telepathic link to issue commands to the creature while you are conscious (no action required), which it does its best to obey.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("not charmed".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Druid, SpellClass::Sorcerer],
    });

    db.insert("evard's black tentacles".to_string(), SpellData {
        name: "Evard's Black Tentacles".to_string(),
        level: 4,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(90),
        components: Components::vsm("a piece of tentacle from a giant octopus or a giant squid"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "Squirming, ebony tentacles fill a 20-foot square on ground that you can see within range. For the duration, these tentacles turn the ground in the area into difficult terrain. When a creature enters the affected area for the first time on a turn or starts its turn there, the creature must succeed on a Dexterity saving throw or take 3d6 bludgeoning damage and be restrained by the tentacles until the spell ends.".to_string(),
        damage_dice: Some("3d6".to_string()),
        damage_type: Some(DamageType::Bludgeoning),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("not restrained".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Cube(20),
        classes: vec![SpellClass::Wizard],
    });

    db.insert("fabricate".to_string(), SpellData {
        name: "Fabricate".to_string(),
        level: 4,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Minutes(10),
        range: SpellRange::Feet(120),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You convert raw materials into products of the same material. For example, you can fabricate a wooden bridge from a clump of trees, a rope from a patch of hemp, and clothes from flax or wool. Choose raw materials that you can see within range. You can fabricate a Large or smaller object (contained within a 10-foot cube) given a sufficient quantity of raw material. If you are working with metal, stone, or another mineral substance, the fabricated object can be no larger than Medium.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Cube(10),
        classes: vec![SpellClass::Wizard],
    });

    db.insert("freedom of movement".to_string(), SpellData {
        name: "Freedom of Movement".to_string(),
        level: 4,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("a leather strap, bound around the arm or a similar appendage"),
        duration: SpellDuration::Hours(1),
        concentration: false,
        ritual: false,
        description: "You touch a willing creature. For the duration, the target's movement is unaffected by difficult terrain, and spells and other magical effects can neither reduce the target's speed nor cause the target to be paralyzed or restrained. The target can also spend 5 feet of movement to automatically escape from nonmagical restraints. Additionally, being underwater imposes no penalties on the target's movement or attacks.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Druid, SpellClass::Ranger],
    });

    db.insert("giant insect".to_string(), SpellData {
        name: "Giant Insect".to_string(),
        level: 4,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vs(),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "You transform up to ten centipedes, three spiders, five wasps, or one scorpion within range into giant versions of their natural forms for the duration. A centipede becomes a giant centipede, a spider becomes a giant spider, a wasp becomes a giant wasp, and a scorpion becomes a giant scorpion. Each creature obeys your verbal commands and takes its turn on your initiative. The DM has the statistics for these creatures.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Druid],
    });

    db.insert("grasping vine".to_string(), SpellData {
        name: "Grasping Vine".to_string(),
        level: 4,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::BonusAction,
        range: SpellRange::Feet(30),
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "You conjure a vine that sprouts from the ground in an unoccupied space of your choice that you can see within range. When you cast this spell, you can direct the vine to lash out at a creature within 30 feet of it. That creature must succeed on a Dexterity saving throw or be pulled 20 feet directly toward the vine. Until the spell ends, you can direct the vine to lash out at the same creature or another one as a bonus action on each of your turns.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("not pulled".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Druid, SpellClass::Ranger],
    });

    db.insert("guardian of faith".to_string(), SpellData {
        name: "Guardian of Faith".to_string(),
        level: 4,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::v(),
        duration: SpellDuration::Hours(8),
        concentration: false,
        ritual: false,
        description: "A Large spectral guardian appears and hovers for the duration in an unoccupied space of your choice that you can see within range. The guardian occupies that space and is indistinct except for a gleaming sword and shield emblazoned with the symbol of your deity. Any creature hostile to you that moves to a space within 10 feet of the guardian for the first time on a turn must succeed on a Dexterity saving throw. The creature takes 20 radiant damage on a failed save, or half as much on a successful one. The guardian vanishes when it has dealt a total of 60 damage.".to_string(),
        damage_dice: None,
        damage_type: Some(DamageType::Radiant),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric],
    });

    db.insert("hallucinatory terrain".to_string(), SpellData {
        name: "Hallucinatory Terrain".to_string(),
        level: 4,
        school: SpellSchool::Illusion,
        casting_time: CastingTime::Minutes(10),
        range: SpellRange::Feet(300),
        components: Components::vsm("a stone, a twig, and a bit of green plant"),
        duration: SpellDuration::Hours(24),
        concentration: false,
        ritual: false,
        description: "You make natural terrain in a 150-foot cube in range look, sound, and smell like some other sort of natural terrain. Thus, open fields or a road can be made to resemble a swamp, hill, crevasse, or some other difficult or impassable terrain. A pond can be made to seem like a grassy meadow, a precipice like a gentle slope, or a rock-strewn gully like a wide and smooth road. The spell doesn't disguise, conceal, or add creatures.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Cube(150),
        classes: vec![SpellClass::Bard, SpellClass::Druid, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("locate creature".to_string(), SpellData {
        name: "Locate Creature".to_string(),
        level: 4,
        school: SpellSchool::Divination,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vsm("a bit of fur from a bloodhound"),
        duration: SpellDuration::Hours(1),
        concentration: true,
        ritual: false,
        description: "Describe or name a creature that is familiar to you. You sense the direction to the creature's location, as long as that creature is within 1,000 feet of you. If the creature is moving, you know the direction of its movement. The spell can locate a specific creature known to you, or the nearest creature of a specific kind, as long as you have seen such a creature up close within 30 feet at least once. Running water blocks this spell.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Druid, SpellClass::Paladin, SpellClass::Ranger, SpellClass::Wizard],
    });

    db.insert("mordenkainen's private sanctum".to_string(), SpellData {
        name: "Mordenkainen's Private Sanctum".to_string(),
        level: 4,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Minutes(10),
        range: SpellRange::Feet(120),
        components: Components::vsm("a thin sheet of lead, a piece of opaque glass, a wad of cotton or cloth, and powdered chrysolite"),
        duration: SpellDuration::Hours(24),
        concentration: false,
        ritual: false,
        description: "You make an area within range magically secure. The area is a cube that can be as small as 5 feet to as large as 100 feet on each side. The spell lasts for the duration or until you use an action to dismiss it. You decide what the security is when you cast the spell: sound can't pass through the barrier, the barrier is opaque, sensors can't appear inside, divination spells can't target creatures inside, nothing can teleport in or out, and planar travel is blocked.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Cube(100),
        classes: vec![SpellClass::Wizard],
    });

    db.insert("otiluke's resilient sphere".to_string(), SpellData {
        name: "Otiluke's Resilient Sphere".to_string(),
        level: 4,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vsm("a hemispherical piece of clear crystal and a matching hemispherical piece of gum arabic"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "A sphere of shimmering force encloses a creature or object of Large size or smaller within range. An unwilling creature must make a Dexterity saving throw. On a failed save, the creature is enclosed for the duration. Nothing, not physical objects, energy, or other spell effects, can pass through the barrier, in or out, though a creature in the sphere can breathe there. The sphere is immune to all damage, and a creature or object inside can't be damaged by attacks or effects originating from outside.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("not enclosed".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Wizard],
    });

    db.insert("phantasmal killer".to_string(), SpellData {
        name: "Phantasmal Killer".to_string(),
        level: 4,
        school: SpellSchool::Illusion,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "You tap into the nightmares of a creature you can see within range and create an illusory manifestation of its deepest fears, visible only to that creature. The target must make a Wisdom saving throw. On a failed save, the target becomes frightened for the duration. At the end of each of the target's turns before the spell ends, the target must succeed on a Wisdom saving throw or take 4d10 psychic damage. On a successful save, the spell ends.".to_string(),
        damage_dice: Some("4d10".to_string()),
        damage_type: Some(DamageType::Psychic),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d10".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("spell ends".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Wizard],
    });

    db.insert("stone shape".to_string(), SpellData {
        name: "Stone Shape".to_string(),
        level: 4,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("soft clay, which must be worked into roughly the desired shape of the stone object"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You touch a stone object of Medium size or smaller or a section of stone no more than 5 feet in any dimension and form it into any shape that suits your purpose. So, for example, you could shape a large rock into a weapon, idol, or coffer, or make a small passage through a wall, as long as the wall is less than 5 feet thick. You could also shape a stone door or its frame to seal the door shut. The object you create can have up to two hinges and a latch, but finer mechanical detail isn't possible.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Druid, SpellClass::Wizard],
    });
}
