//! 8th level spell definitions.

use super::types::*;
use crate::rules::DamageType;
use crate::world::Ability;
use std::collections::HashMap;

/// Register all 8th level spells into the spell database.
pub fn register_level8(db: &mut HashMap<String, SpellData>) {
    db.insert("antimagic field".to_string(), SpellData {
        name: "Antimagic Field".to_string(),
        level: 8,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::SelfRadius(10),
        components: Components::vsm("a pinch of powdered iron or iron filings"),
        duration: SpellDuration::Hours(1),
        concentration: true,
        ritual: false,
        description: "A 10-foot-radius invisible sphere of antimagic surrounds you. This area is divorced from the magical energy that suffuses the multiverse. Within the sphere, spells can't be cast, summoned creatures disappear, and even magic items become mundane. Until the spell ends, the sphere moves with you, centered on you.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(10),
        classes: vec![SpellClass::Cleric, SpellClass::Wizard],
    });

    db.insert("dominate monster".to_string(), SpellData {
        name: "Dominate Monster".to_string(),
        level: 8,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vs(),
        duration: SpellDuration::Hours(1),
        concentration: true,
        ritual: false,
        description: "You attempt to beguile a creature that you can see within range. It must succeed on a Wisdom saving throw or be charmed by you for the duration. If you or creatures that are friendly to you are fighting it, it has advantage on the saving throw. While the creature is charmed, you have a telepathic link with it. You can use this telepathic link to issue commands to the creature.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("not charmed".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("earthquake".to_string(), SpellData {
        name: "Earthquake".to_string(),
        level: 8,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(500),
        components: Components::vsm("a pinch of dirt, a piece of rock, and a lump of clay"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "You create a seismic disturbance at a point on the ground that you can see within range. For the duration, an intense tremor rips through the ground in a 100-foot-radius circle centered on that point and shakes creatures and structures in contact with the ground. The ground becomes difficult terrain. Each creature on the ground that is concentrating must make a Constitution saving throw or lose concentration.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("avoids fissure".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(100),
        classes: vec![SpellClass::Cleric, SpellClass::Druid, SpellClass::Sorcerer],
    });

    db.insert("incendiary cloud".to_string(), SpellData {
        name: "Incendiary Cloud".to_string(),
        level: 8,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(150),
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "A swirling cloud of smoke shot through with white-hot embers appears in a 20-foot-radius sphere centered on a point within range. The cloud spreads around corners and is heavily obscured. When the cloud appears, each creature in it must make a Dexterity saving throw. A creature takes 10d8 fire damage on a failed save, or half as much damage on a successful one. A creature must also make this saving throw when it enters the spell's area for the first time on a turn or ends its turn there.".to_string(),
        damage_dice: Some("10d8".to_string()),
        damage_type: Some(DamageType::Fire),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(20),
        classes: vec![SpellClass::Druid, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("power word stun".to_string(), SpellData {
        name: "Power Word Stun".to_string(),
        level: 8,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::v(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You speak a word of power that can overwhelm the mind of one creature you can see within range, leaving it dumbfounded. If the target has 150 hit points or fewer, it is stunned. Otherwise, the spell has no effect. The stunned target must make a Constitution saving throw at the end of each of its turns. On a successful save, this stunning effect ends.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("ends stun".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("sunburst".to_string(), SpellData {
        name: "Sunburst".to_string(),
        level: 8,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(150),
        components: Components::vsm("fire and a piece of sunstone"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "Brilliant sunlight flashes in a 60-foot radius centered on a point you choose within range. Each creature in that light must make a Constitution saving throw. On a failed save, a creature takes 12d6 radiant damage and is blinded for 1 minute. On a successful save, it takes half as much damage and isn't blinded. Undead and oozes have disadvantage on this saving throw.".to_string(),
        damage_dice: Some("12d6".to_string()),
        damage_type: Some(DamageType::Radiant),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("half damage, not blinded".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(60),
        classes: vec![SpellClass::Cleric, SpellClass::Druid, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("antipathy/sympathy".to_string(), SpellData {
        name: "Antipathy/Sympathy".to_string(),
        level: 8,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Hours(1),
        range: SpellRange::Feet(60),
        components: Components::vsm("either a lump of alum soaked in vinegar for antipathy or a drop of honey for sympathy"),
        duration: SpellDuration::Days(10),
        concentration: false,
        ritual: false,
        description: "This spell attracts or repels creatures of your choice. You target something within range, either a Huge or smaller object or creature or an area no larger than a 200-foot cube. Then specify a kind of intelligent creature, such as red dragons, goblins, or vampires. You invest the target with an aura that either attracts or repels the specified creatures for the duration. Choose antipathy (creatures must make a Wisdom save or be frightened and flee) or sympathy (creatures must make a Wisdom save or approach and protect the target).".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("resists effect".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Cube(200),
        classes: vec![SpellClass::Bard, SpellClass::Druid, SpellClass::Wizard],
    });

    db.insert("clone".to_string(), SpellData {
        name: "Clone".to_string(),
        level: 8,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Hours(1),
        range: SpellRange::Touch,
        components: Components::vsm("a diamond worth at least 1,000 gp and at least 1 cubic inch of flesh of the creature that is to be cloned, which the spell consumes, and a vessel worth at least 2,000 gp that has a sealable lid and is large enough to hold the creature being cloned"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "This spell grows an inert duplicate of a living creature as a safeguard against death. This clone forms inside the vessel and grows to full size and maturity after 120 days. At any time after the clone matures, if the original creature dies, its soul transfers to the clone, provided that the soul is free and willing. The clone is physically identical to the original and has the same personality, memories, and abilities, but none of the original's equipment.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Wizard],
    });

    db.insert("control weather".to_string(), SpellData {
        name: "Control Weather".to_string(),
        level: 8,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Minutes(10),
        range: SpellRange::Self_,
        components: Components::vsm("burning incense and bits of earth and wood mixed in water"),
        duration: SpellDuration::Hours(8),
        concentration: true,
        ritual: false,
        description: "You take control of the weather within 5 miles of you for the duration. You must be outdoors to cast this spell. Moving to a place where you don't have a clear path to the sky ends the spell early. When you cast the spell, you change the current weather conditions, which are determined by the DM based on climate and season. You can change precipitation, temperature, and wind. It takes 1d4 x 10 minutes for the new conditions to take effect.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Druid, SpellClass::Wizard],
    });

    db.insert("demiplane".to_string(), SpellData {
        name: "Demiplane".to_string(),
        level: 8,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::s(),
        duration: SpellDuration::Hours(1),
        concentration: false,
        ritual: false,
        description: "You create a shadowy door on a flat solid surface that you can see within range. The door is large enough to allow Medium creatures to pass through unhindered. When opened, the door leads to a demiplane that appears to be an empty room 30 feet in each dimension, made of wood or stone. When the spell ends, the door disappears, and any creatures or objects inside the demiplane remain trapped there. Each time you cast this spell, you can create a new demiplane or have the door connect to a demiplane you created with a previous casting of this spell.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("feeblemind".to_string(), SpellData {
        name: "Feeblemind".to_string(),
        level: 8,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(150),
        components: Components::vsm("a handful of clay, crystal, glass, or mineral spheres"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You blast the mind of a creature that you can see within range, attempting to shatter its intellect and personality. The target takes 4d6 psychic damage and must make an Intelligence saving throw. On a failed save, the creature's Intelligence and Charisma scores become 1. The creature can't cast spells, activate magic items, understand language, or communicate in any intelligible way. The creature can, however, identify its friends, follow them, and even protect them. The creature can repeat the saving throw every 30 days.".to_string(),
        damage_dice: Some("4d6".to_string()),
        damage_type: Some(DamageType::Psychic),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Intelligence),
        save_effect: Some("no INT/CHA reduction".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Druid, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("glibness".to_string(), SpellData {
        name: "Glibness".to_string(),
        level: 8,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::v(),
        duration: SpellDuration::Hours(1),
        concentration: false,
        ritual: false,
        description: "Until the spell ends, when you make a Charisma check, you can replace the number you roll with a 15. Additionally, no matter what you say, magic that would determine if you are telling the truth indicates that you are being truthful.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Warlock],
    });

    db.insert("holy aura".to_string(), SpellData {
        name: "Holy Aura".to_string(),
        level: 8,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vsm("a tiny reliquary worth at least 1,000 gp containing a sacred relic, such as a scrap of cloth from a saint's robe or a piece of parchment from a religious text"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "Divine light washes out from you and coalesces in a soft radiance in a 30-foot radius around you. Creatures of your choice in that radius when you cast this spell shed dim light in a 5-foot radius and have advantage on all saving throws, and other creatures have disadvantage on attack rolls against them. In addition, when a fiend or an undead hits an affected creature with a melee attack, the aura flashes with brilliant light. The attacker must succeed on a Constitution saving throw or be blinded until the spell ends.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("not blinded".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(30),
        classes: vec![SpellClass::Cleric],
    });

    db.insert("maze".to_string(), SpellData {
        name: "Maze".to_string(),
        level: 8,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vs(),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "You banish a creature that you can see within range into a labyrinthine demiplane. The target remains there for the duration or until it escapes the maze. The target can use its action to attempt to escape. When it does so, it makes a DC 20 Intelligence check. If it succeeds, it escapes, and the spell ends. A minotaur or goristro demon automatically succeeds. When the spell ends, the target reappears in the space it left or, if that space is occupied, in the nearest unoccupied space.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Wizard],
    });

    db.insert("mind blank".to_string(), SpellData {
        name: "Mind Blank".to_string(),
        level: 8,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vs(),
        duration: SpellDuration::Hours(24),
        concentration: false,
        ritual: false,
        description: "Until the spell ends, one willing creature you touch is immune to psychic damage, any effect that would sense its emotions or read its thoughts, divination spells, and the charmed condition. The spell even foils wish spells and spells or effects of similar power used to affect the target's mind or to gain information about the target.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Wizard],
    });

    db.insert("telepathy".to_string(), SpellData {
        name: "Telepathy".to_string(),
        level: 8,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Unlimited,
        components: Components::vsm("a pair of linked silver rings"),
        duration: SpellDuration::Hours(24),
        concentration: false,
        ritual: false,
        description: "You create a telepathic link between yourself and a willing creature with which you are familiar. The creature can be anywhere on the same plane of existence as you. Until the spell ends, you and the target can instantaneously share words, images, sounds, and other sensory messages with one another through the link, and the target recognizes you as the creature it is communicating with. The spell enables a creature with an Intelligence score of at least 1 to understand the meaning of your words and take in the scope of any sensory messages you send to it.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Wizard],
    });
}
