//! 3rd level spell definitions.

use super::types::*;
use crate::rules::DamageType;
use crate::world::Ability;
use std::collections::HashMap;

/// Register all 3rd level spells into the spell database.
pub fn register_level3(db: &mut HashMap<String, SpellData>) {
    db.insert("fireball".to_string(), SpellData {
        name: "Fireball".to_string(),
        level: 3,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(150),
        components: Components::vsm("a tiny ball of bat guano and sulfur"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "A bright streak flashes from your pointing finger to a point you choose within range and then blossoms with a low roar into an explosion of flame. Each creature in a 20-foot-radius sphere centered on that point must make a Dexterity saving throw. A target takes 8d6 fire damage on a failed save, or half as much damage on a successful one.".to_string(),
        damage_dice: Some("8d6".to_string()),
        damage_type: Some(DamageType::Fire),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d6".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(20),
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("lightning bolt".to_string(), SpellData {
        name: "Lightning Bolt".to_string(),
        level: 3,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::SelfLine(100, 5),
        components: Components::vsm("a bit of fur and a rod of amber, crystal, or glass"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "A stroke of lightning forming a line 100 feet long and 5 feet wide blasts out from you in a direction you choose. Each creature in the line must make a Dexterity saving throw. A creature takes 8d6 lightning damage on a failed save, or half as much damage on a successful one.".to_string(),
        damage_dice: Some("8d6".to_string()),
        damage_type: Some(DamageType::Lightning),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d6".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Line(100, 5),
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("counterspell".to_string(), SpellData {
        name: "Counterspell".to_string(),
        level: 3,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Reaction("which you take when you see a creature within 60 feet casting a spell".to_string()),
        range: SpellRange::Feet(60),
        components: Components::s(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You attempt to interrupt a creature in the process of casting a spell. If the creature is casting a spell of 3rd level or lower, its spell fails. If it is casting a spell of 4th level or higher, make an ability check using your spellcasting ability. The DC equals 10 + the spell's level. On a success, the creature's spell fails.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("dispel magic".to_string(), SpellData {
        name: "Dispel Magic".to_string(),
        level: 3,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "Choose one creature, object, or magical effect within range. Any spell of 3rd level or lower on the target ends. For each spell of 4th level or higher on the target, make an ability check using your spellcasting ability. The DC equals 10 + the spell's level. On a successful check, the spell ends.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Druid, SpellClass::Paladin, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("spirit guardians".to_string(), SpellData {
        name: "Spirit Guardians".to_string(),
        level: 3,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::SelfRadius(15),
        components: Components::vsm("a holy symbol"),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "You call forth spirits to protect you. They flit around you to a distance of 15 feet for the duration. When a creature enters the area for the first time on a turn or starts its turn there, it must make a Wisdom saving throw. On a failed save, the creature takes 3d8 radiant damage (if you are good or neutral) or 3d8 necrotic damage (if you are evil). On a successful save, the creature takes half as much damage.".to_string(),
        damage_dice: Some("3d8".to_string()),
        damage_type: Some(DamageType::Radiant),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d8".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(15),
        classes: vec![SpellClass::Cleric],
    });

    db.insert("animate dead".to_string(), SpellData {
        name: "Animate Dead".to_string(),
        level: 3,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Minutes(1),
        range: SpellRange::Feet(10),
        components: Components::vsm("a drop of blood, a piece of flesh, and a pinch of bone dust"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "This spell creates an undead servant. Choose a pile of bones or a corpse of a Medium or Small humanoid within range. Your spell imbues the target with a foul mimicry of life, raising it as an undead creature. The target becomes a skeleton if you chose bones or a zombie if you chose a corpse.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Wizard],
    });

    db.insert("aura of vitality".to_string(), SpellData {
        name: "Aura of Vitality".to_string(),
        level: 3,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::SelfRadius(30),
        components: Components::v(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "Healing energy radiates from you in an aura with a 30-foot radius. You can use a bonus action to cause one creature in the aura to regain 2d6 hit points.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: Some("2d6".to_string()),
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(30),
        classes: vec![SpellClass::Cleric, SpellClass::Druid, SpellClass::Paladin],
    });

    db.insert("beacon of hope".to_string(), SpellData {
        name: "Beacon of Hope".to_string(),
        level: 3,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "This spell bestows hope and vitality. Choose any number of creatures within range. For the duration, each target has advantage on Wisdom saving throws and death saving throws, and regains the maximum number of hit points possible from any healing.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric],
    });

    db.insert("bestow curse".to_string(), SpellData {
        name: "Bestow Curse".to_string(),
        level: 3,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "You touch a creature, and that creature must succeed on a Wisdom saving throw or become cursed for the duration of the spell.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("negates".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Wizard],
    });

    db.insert("blink".to_string(), SpellData {
        name: "Blink".to_string(),
        level: 3,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: false,
        ritual: false,
        description: "Roll a d20 at the end of each of your turns. On a roll of 11 or higher, you vanish from your current plane and appear in the Ethereal Plane.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("call lightning".to_string(), SpellData {
        name: "Call Lightning".to_string(),
        level: 3,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vs(),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "A storm cloud appears. Each creature within 5 feet of a chosen point must make a Dexterity saving throw. A creature takes 3d10 lightning damage on a failed save, or half as much on a successful one.".to_string(),
        damage_dice: Some("3d10".to_string()),
        damage_type: Some(DamageType::Lightning),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d10".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Cylinder(60, 10),
        classes: vec![SpellClass::Druid],
    });

    db.insert(
        "clairvoyance".to_string(),
        SpellData {
            name: "Clairvoyance".to_string(),
            level: 3,
            school: SpellSchool::Divination,
            casting_time: CastingTime::Minutes(10),
            range: SpellRange::Miles(1),
            components: Components::vsm("a focus worth at least 100 gp"),
            duration: SpellDuration::Minutes(10),
            concentration: true,
            ritual: false,
            description:
                "You create an invisible sensor within range in a location familiar to you."
                    .to_string(),
            damage_dice: None,
            damage_type: None,
            damage_scaling: DamageScaling::None,
            healing_dice: None,
            save_type: None,
            save_effect: None,
            attack_type: None,
            area_of_effect: AreaOfEffect::None,
            classes: vec![
                SpellClass::Bard,
                SpellClass::Cleric,
                SpellClass::Sorcerer,
                SpellClass::Wizard,
            ],
        },
    );

    db.insert(
        "conjure animals".to_string(),
        SpellData {
            name: "Conjure Animals".to_string(),
            level: 3,
            school: SpellSchool::Conjuration,
            casting_time: CastingTime::Action,
            range: SpellRange::Feet(60),
            components: Components::vs(),
            duration: SpellDuration::Hours(1),
            concentration: true,
            ritual: false,
            description: "You summon fey spirits that take the form of beasts.".to_string(),
            damage_dice: None,
            damage_type: None,
            damage_scaling: DamageScaling::None,
            healing_dice: None,
            save_type: None,
            save_effect: None,
            attack_type: None,
            area_of_effect: AreaOfEffect::None,
            classes: vec![SpellClass::Druid, SpellClass::Ranger],
        },
    );

    db.insert(
        "create food and water".to_string(),
        SpellData {
            name: "Create Food and Water".to_string(),
            level: 3,
            school: SpellSchool::Conjuration,
            casting_time: CastingTime::Action,
            range: SpellRange::Feet(30),
            components: Components::vs(),
            duration: SpellDuration::Instantaneous,
            concentration: false,
            ritual: false,
            description: "You create 45 pounds of food and 30 gallons of water.".to_string(),
            damage_dice: None,
            damage_type: None,
            damage_scaling: DamageScaling::None,
            healing_dice: None,
            save_type: None,
            save_effect: None,
            attack_type: None,
            area_of_effect: AreaOfEffect::None,
            classes: vec![SpellClass::Cleric, SpellClass::Paladin],
        },
    );

    db.insert(
        "daylight".to_string(),
        SpellData {
            name: "Daylight".to_string(),
            level: 3,
            school: SpellSchool::Evocation,
            casting_time: CastingTime::Action,
            range: SpellRange::Feet(60),
            components: Components::vs(),
            duration: SpellDuration::Hours(1),
            concentration: false,
            ritual: false,
            description:
                "A 60-foot-radius sphere of light spreads out from a point you choose within range."
                    .to_string(),
            damage_dice: None,
            damage_type: None,
            damage_scaling: DamageScaling::None,
            healing_dice: None,
            save_type: None,
            save_effect: None,
            attack_type: None,
            area_of_effect: AreaOfEffect::Sphere(60),
            classes: vec![
                SpellClass::Cleric,
                SpellClass::Druid,
                SpellClass::Paladin,
                SpellClass::Ranger,
                SpellClass::Sorcerer,
            ],
        },
    );

    db.insert("fear".to_string(), SpellData {
        name: "Fear".to_string(),
        level: 3,
        school: SpellSchool::Illusion,
        casting_time: CastingTime::Action,
        range: SpellRange::SelfCone(30),
        components: Components::vsm("a white feather or the heart of a hen"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "You project a phantasmal image of a creature's worst fears. Each creature in a 30-foot cone must succeed on a Wisdom saving throw or become frightened.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("negates".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Cone(30),
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("feign death".to_string(), SpellData {
        name: "Feign Death".to_string(),
        level: 3,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("a pinch of graveyard dirt"),
        duration: SpellDuration::Hours(1),
        concentration: false,
        ritual: true,
        description: "You touch a willing creature and put it into a cataleptic state indistinguishable from death.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Druid, SpellClass::Wizard],
    });

    db.insert("fly".to_string(), SpellData {
        name: "Fly".to_string(),
        level: 3,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("a wing feather from any bird"),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "You touch a willing creature. The target gains a flying speed of 60 feet for the duration.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert(
        "gaseous form".to_string(),
        SpellData {
            name: "Gaseous Form".to_string(),
            level: 3,
            school: SpellSchool::Transmutation,
            casting_time: CastingTime::Action,
            range: SpellRange::Touch,
            components: Components::vsm("a bit of gauze and a wisp of smoke"),
            duration: SpellDuration::Hours(1),
            concentration: true,
            ritual: false,
            description:
                "You transform a willing creature you touch into a misty cloud for the duration."
                    .to_string(),
            damage_dice: None,
            damage_type: None,
            damage_scaling: DamageScaling::None,
            healing_dice: None,
            save_type: None,
            save_effect: None,
            attack_type: None,
            area_of_effect: AreaOfEffect::None,
            classes: vec![
                SpellClass::Sorcerer,
                SpellClass::Warlock,
                SpellClass::Wizard,
            ],
        },
    );

    db.insert(
        "glyph of warding".to_string(),
        SpellData {
            name: "Glyph of Warding".to_string(),
            level: 3,
            school: SpellSchool::Abjuration,
            casting_time: CastingTime::Hours(1),
            range: SpellRange::Touch,
            components: Components::vsm(
                "incense and powdered diamond worth at least 200 gp, which the spell consumes",
            ),
            duration: SpellDuration::UntilDispelled,
            concentration: false,
            ritual: false,
            description: "You inscribe a glyph that later unleashes a magical effect.".to_string(),
            damage_dice: Some("5d8".to_string()),
            damage_type: None,
            damage_scaling: DamageScaling::PerSlotLevel {
                extra_dice: "1d8".to_string(),
            },
            healing_dice: None,
            save_type: Some(Ability::Dexterity),
            save_effect: Some("half damage".to_string()),
            attack_type: None,
            area_of_effect: AreaOfEffect::Sphere(20),
            classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Wizard],
        },
    );

    db.insert("haste".to_string(), SpellData {
        name: "Haste".to_string(),
        level: 3,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vsm("a shaving of licorice root"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "Choose a willing creature. The target's speed is doubled, it gains +2 AC, advantage on Dexterity saves, and an additional action each turn.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("hunger of hadar".to_string(), SpellData {
        name: "Hunger of Hadar".to_string(),
        level: 3,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(150),
        components: Components::vsm("a pickled octopus tentacle"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "A 20-foot-radius sphere of blackness and cold appears. Creatures take 2d6 cold damage at start of turn and 2d6 acid damage on failed DEX save at end of turn.".to_string(),
        damage_dice: Some("2d6".to_string()),
        damage_type: Some(DamageType::Cold),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("negates acid damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(20),
        classes: vec![SpellClass::Warlock],
    });

    db.insert("hypnotic pattern".to_string(), SpellData {
        name: "Hypnotic Pattern".to_string(),
        level: 3,
        school: SpellSchool::Illusion,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::sm("a glowing stick of incense or a crystal vial filled with phosphorescent material"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "You create a twisting pattern of colors in a 30-foot cube. Each creature who sees it must make a Wisdom save or become charmed and incapacitated.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("negates".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Cube(30),
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert(
        "leomund's tiny hut".to_string(),
        SpellData {
            name: "Leomund's Tiny Hut".to_string(),
            level: 3,
            school: SpellSchool::Evocation,
            casting_time: CastingTime::Minutes(1),
            range: SpellRange::SelfRadius(10),
            components: Components::vsm("a small crystal bead"),
            duration: SpellDuration::Hours(8),
            concentration: false,
            ritual: true,
            description:
                "A 10-foot-radius immobile dome of force springs into existence around you."
                    .to_string(),
            damage_dice: None,
            damage_type: None,
            damage_scaling: DamageScaling::None,
            healing_dice: None,
            save_type: None,
            save_effect: None,
            attack_type: None,
            area_of_effect: AreaOfEffect::Sphere(10),
            classes: vec![SpellClass::Bard, SpellClass::Wizard],
        },
    );

    db.insert("major image".to_string(), SpellData {
        name: "Major Image".to_string(),
        level: 3,
        school: SpellSchool::Illusion,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vsm("a bit of fleece"),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "You create the image of an object, creature, or phenomenon no larger than a 20-foot cube.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Cube(20),
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("mass healing word".to_string(), SpellData {
        name: "Mass Healing Word".to_string(),
        level: 3,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::BonusAction,
        range: SpellRange::Feet(60),
        components: Components::v(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "Up to six creatures of your choice regain hit points equal to 1d4 + your spellcasting ability modifier.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: Some("1d4".to_string()),
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric],
    });

    db.insert(
        "meld into stone".to_string(),
        SpellData {
            name: "Meld into Stone".to_string(),
            level: 3,
            school: SpellSchool::Transmutation,
            casting_time: CastingTime::Action,
            range: SpellRange::Touch,
            components: Components::vs(),
            duration: SpellDuration::Hours(8),
            concentration: false,
            ritual: true,
            description:
                "You step into a stone object or surface large enough to contain your body."
                    .to_string(),
            damage_dice: None,
            damage_type: None,
            damage_scaling: DamageScaling::None,
            healing_dice: None,
            save_type: None,
            save_effect: None,
            attack_type: None,
            area_of_effect: AreaOfEffect::None,
            classes: vec![SpellClass::Cleric, SpellClass::Druid],
        },
    );

    db.insert(
        "nondetection".to_string(),
        SpellData {
            name: "Nondetection".to_string(),
            level: 3,
            school: SpellSchool::Abjuration,
            casting_time: CastingTime::Action,
            range: SpellRange::Touch,
            components: Components::vsm(
                "a pinch of diamond dust worth 25 gp, which the spell consumes",
            ),
            duration: SpellDuration::Hours(8),
            concentration: false,
            ritual: false,
            description: "You hide a target from divination magic.".to_string(),
            damage_dice: None,
            damage_type: None,
            damage_scaling: DamageScaling::None,
            healing_dice: None,
            save_type: None,
            save_effect: None,
            attack_type: None,
            area_of_effect: AreaOfEffect::None,
            classes: vec![SpellClass::Bard, SpellClass::Ranger, SpellClass::Wizard],
        },
    );

    db.insert(
        "phantom steed".to_string(),
        SpellData {
            name: "Phantom Steed".to_string(),
            level: 3,
            school: SpellSchool::Illusion,
            casting_time: CastingTime::Minutes(1),
            range: SpellRange::Feet(30),
            components: Components::vs(),
            duration: SpellDuration::Hours(1),
            concentration: false,
            ritual: true,
            description: "A Large quasi-real, horselike creature appears with a speed of 100 feet."
                .to_string(),
            damage_dice: None,
            damage_type: None,
            damage_scaling: DamageScaling::None,
            healing_dice: None,
            save_type: None,
            save_effect: None,
            attack_type: None,
            area_of_effect: AreaOfEffect::None,
            classes: vec![SpellClass::Wizard],
        },
    );

    db.insert("plant growth".to_string(), SpellData {
        name: "Plant Growth".to_string(),
        level: 3,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(150),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "All normal plants in a 100-foot radius become thick and overgrown, creating difficult terrain.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(100),
        classes: vec![SpellClass::Bard, SpellClass::Druid, SpellClass::Ranger],
    });

    db.insert("protection from energy".to_string(), SpellData {
        name: "Protection from Energy".to_string(),
        level: 3,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vs(),
        duration: SpellDuration::Hours(1),
        concentration: true,
        ritual: false,
        description: "The willing creature you touch has resistance to acid, cold, fire, lightning, or thunder damage.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Druid, SpellClass::Ranger, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert(
        "remove curse".to_string(),
        SpellData {
            name: "Remove Curse".to_string(),
            level: 3,
            school: SpellSchool::Abjuration,
            casting_time: CastingTime::Action,
            range: SpellRange::Touch,
            components: Components::vs(),
            duration: SpellDuration::Instantaneous,
            concentration: false,
            ritual: false,
            description: "At your touch, all curses affecting one creature or object end."
                .to_string(),
            damage_dice: None,
            damage_type: None,
            damage_scaling: DamageScaling::None,
            healing_dice: None,
            save_type: None,
            save_effect: None,
            attack_type: None,
            area_of_effect: AreaOfEffect::None,
            classes: vec![
                SpellClass::Cleric,
                SpellClass::Paladin,
                SpellClass::Warlock,
                SpellClass::Wizard,
            ],
        },
    );

    db.insert("revivify".to_string(), SpellData {
        name: "Revivify".to_string(),
        level: 3,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("diamonds worth 300 gp, which the spell consumes"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You touch a creature that has died within the last minute. That creature returns to life with 1 hit point.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Paladin],
    });

    db.insert("sending".to_string(), SpellData {
        name: "Sending".to_string(),
        level: 3,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Unlimited,
        components: Components::vsm("a short piece of fine copper wire"),
        duration: SpellDuration::Rounds(1),
        concentration: false,
        ritual: false,
        description: "You send a short message of twenty-five words or less to a creature with which you are familiar.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Wizard],
    });

    db.insert("sleet storm".to_string(), SpellData {
        name: "Sleet Storm".to_string(),
        level: 3,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(150),
        components: Components::vsm("a pinch of dust and a few drops of water"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "Freezing rain and sleet fall in a 20-foot-tall cylinder with a 40-foot radius. Creatures must make a DEX save or fall prone.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("negates prone".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Cylinder(40, 20),
        classes: vec![SpellClass::Druid, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("slow".to_string(), SpellData {
        name: "Slow".to_string(),
        level: 3,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vsm("a drop of molasses"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "Up to six creatures in a 40-foot cube must make a WIS save or have their speed halved, -2 AC, and limited actions.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("negates".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Cube(40),
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert(
        "speak with dead".to_string(),
        SpellData {
            name: "Speak with Dead".to_string(),
            level: 3,
            school: SpellSchool::Necromancy,
            casting_time: CastingTime::Action,
            range: SpellRange::Feet(10),
            components: Components::vsm("burning incense"),
            duration: SpellDuration::Minutes(10),
            concentration: false,
            ritual: false,
            description: "You grant life to a corpse allowing it to answer up to five questions."
                .to_string(),
            damage_dice: None,
            damage_type: None,
            damage_scaling: DamageScaling::None,
            healing_dice: None,
            save_type: None,
            save_effect: None,
            attack_type: None,
            area_of_effect: AreaOfEffect::None,
            classes: vec![SpellClass::Bard, SpellClass::Cleric],
        },
    );

    db.insert(
        "speak with plants".to_string(),
        SpellData {
            name: "Speak with Plants".to_string(),
            level: 3,
            school: SpellSchool::Transmutation,
            casting_time: CastingTime::Action,
            range: SpellRange::SelfRadius(30),
            components: Components::vs(),
            duration: SpellDuration::Minutes(10),
            concentration: false,
            ritual: false,
            description: "You imbue plants within 30 feet with limited sentience and animation."
                .to_string(),
            damage_dice: None,
            damage_type: None,
            damage_scaling: DamageScaling::None,
            healing_dice: None,
            save_type: None,
            save_effect: None,
            attack_type: None,
            area_of_effect: AreaOfEffect::Sphere(30),
            classes: vec![SpellClass::Bard, SpellClass::Druid, SpellClass::Ranger],
        },
    );

    db.insert("stinking cloud".to_string(), SpellData {
        name: "Stinking Cloud".to_string(),
        level: 3,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(90),
        components: Components::vsm("a rotten egg or several skunk cabbage leaves"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "A 20-foot-radius sphere of nauseating gas. Creatures must make a CON save or spend their action retching.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("negates".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(20),
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert(
        "summon fey".to_string(),
        SpellData {
            name: "Summon Fey".to_string(),
            level: 3,
            school: SpellSchool::Conjuration,
            casting_time: CastingTime::Action,
            range: SpellRange::Feet(90),
            components: Components::vsm("a gilded flower worth at least 300 gp"),
            duration: SpellDuration::Hours(1),
            concentration: true,
            ritual: false,
            description: "You call forth a fey spirit that obeys your verbal commands.".to_string(),
            damage_dice: None,
            damage_type: None,
            damage_scaling: DamageScaling::None,
            healing_dice: None,
            save_type: None,
            save_effect: None,
            attack_type: None,
            area_of_effect: AreaOfEffect::None,
            classes: vec![
                SpellClass::Druid,
                SpellClass::Ranger,
                SpellClass::Warlock,
                SpellClass::Wizard,
            ],
        },
    );

    db.insert("tongues".to_string(), SpellData {
        name: "Tongues".to_string(),
        level: 3,
        school: SpellSchool::Divination,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("a small clay model of a ziggurat"),
        duration: SpellDuration::Hours(1),
        concentration: false,
        ritual: false,
        description: "The creature you touch can understand any spoken language and be understood by any creature.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("vampiric touch".to_string(), SpellData {
        name: "Vampiric Touch".to_string(),
        level: 3,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "Make a melee spell attack. On hit, the target takes 3d6 necrotic damage and you regain half that amount in hit points.".to_string(),
        damage_dice: Some("3d6".to_string()),
        damage_type: Some(DamageType::Necrotic),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d6".to_string() },
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: Some(SpellAttackType::Melee),
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert(
        "water breathing".to_string(),
        SpellData {
            name: "Water Breathing".to_string(),
            level: 3,
            school: SpellSchool::Transmutation,
            casting_time: CastingTime::Action,
            range: SpellRange::Feet(30),
            components: Components::vsm("a short reed or piece of straw"),
            duration: SpellDuration::Hours(24),
            concentration: false,
            ritual: true,
            description: "Up to ten willing creatures can breathe underwater for the duration."
                .to_string(),
            damage_dice: None,
            damage_type: None,
            damage_scaling: DamageScaling::None,
            healing_dice: None,
            save_type: None,
            save_effect: None,
            attack_type: None,
            area_of_effect: AreaOfEffect::None,
            classes: vec![
                SpellClass::Druid,
                SpellClass::Ranger,
                SpellClass::Sorcerer,
                SpellClass::Wizard,
            ],
        },
    );

    db.insert("water walk".to_string(), SpellData {
        name: "Water Walk".to_string(),
        level: 3,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vsm("a piece of cork"),
        duration: SpellDuration::Hours(1),
        concentration: false,
        ritual: true,
        description: "Up to ten willing creatures can move across any liquid surface as if it were solid ground.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Druid, SpellClass::Ranger, SpellClass::Sorcerer],
    });

    db.insert("wind wall".to_string(), SpellData {
        name: "Wind Wall".to_string(),
        level: 3,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vsm("a tiny fan and a feather of exotic origin"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "A wall of strong wind up to 50 feet long, 15 feet high. Creatures must make a STR save or take 3d8 bludgeoning damage.".to_string(),
        damage_dice: Some("3d8".to_string()),
        damage_type: Some(DamageType::Bludgeoning),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Strength),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Line(50, 1),
        classes: vec![SpellClass::Druid, SpellClass::Ranger],
    });
}
