//! 9th level spell definitions.

use super::types::*;
use crate::rules::DamageType;
use crate::world::Ability;
use std::collections::HashMap;

/// Register all 9th level spells into the spell database.
pub fn register_level9(db: &mut HashMap<String, SpellData>) {
    db.insert("foresight".to_string(), SpellData {
        name: "Foresight".to_string(),
        level: 9,
        school: SpellSchool::Divination,
        casting_time: CastingTime::Minutes(1),
        range: SpellRange::Touch,
        components: Components::vsm("a hummingbird feather"),
        duration: SpellDuration::Hours(8),
        concentration: false,
        ritual: false,
        description: "You touch a willing creature and bestow a limited ability to see into the immediate future. For the duration, the target can't be surprised and has advantage on attack rolls, ability checks, and saving throws. Additionally, other creatures have disadvantage on attack rolls against the target for the duration.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Druid, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("gate".to_string(), SpellData {
        name: "Gate".to_string(),
        level: 9,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vsm("a diamond worth at least 5,000 gp"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "You conjure a portal linking an unoccupied space you can see within range to a precise location on a different plane of existence. The portal is a circular opening, which you can make 5 to 20 feet in diameter. You can orient the portal in any direction you choose. The portal lasts for the duration. When you cast this spell, you can speak the name of a specific creature, and if that creature is on a plane other than the one you are on, the portal opens in the named creature's immediate vicinity.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("mass heal".to_string(), SpellData {
        name: "Mass Heal".to_string(),
        level: 9,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "A flood of healing energy flows from you into injured creatures around you. You restore up to 700 hit points, divided as you choose among any number of creatures that you can see within range. Creatures healed by this spell are also cured of all diseases and any effect making them blinded or deafened. This spell has no effect on undead or constructs.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: Some("700".to_string()),
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(60),
        classes: vec![SpellClass::Cleric],
    });

    db.insert("meteor swarm".to_string(), SpellData {
        name: "Meteor Swarm".to_string(),
        level: 9,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Miles(1),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "Blazing orbs of fire plummet to the ground at four different points you can see within range. Each creature in a 40-foot-radius sphere centered on each point you choose must make a Dexterity saving throw. The sphere spreads around corners. A creature takes 20d6 fire damage and 20d6 bludgeoning damage on a failed save, or half as much damage on a successful one. A creature in the area of more than one fiery burst is affected only once.".to_string(),
        damage_dice: Some("20d6+20d6".to_string()),
        damage_type: Some(DamageType::Fire),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(40),
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("power word kill".to_string(), SpellData {
        name: "Power Word Kill".to_string(),
        level: 9,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::v(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You utter a word of power that can compel one creature you can see within range to die instantly. If the creature you choose has 100 hit points or fewer, it dies. Otherwise, the spell has no effect.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("power word heal".to_string(), SpellData {
        name: "Power Word Heal".to_string(),
        level: 9,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "A wave of healing energy washes over the creature you touch. The target regains all its hit points. If the creature is charmed, frightened, paralyzed, or stunned, the condition ends. If the creature is prone, it can use its reaction to stand up. This spell has no effect on undead or constructs.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric],
    });

    db.insert("true polymorph".to_string(), SpellData {
        name: "True Polymorph".to_string(),
        level: 9,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vsm("a drop of mercury, a dollop of gum arabic, and a wisp of smoke"),
        duration: SpellDuration::Hours(1),
        concentration: true,
        ritual: false,
        description: "Choose one creature or nonmagical object that you can see within range. You transform the creature into a different creature, the creature into a nonmagical object, or the object into a creature. The transformation lasts for the duration, or until the target drops to 0 hit points or dies. If you concentrate on this spell for the full duration, the transformation lasts until it is dispelled.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("not transformed".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("true resurrection".to_string(), SpellData {
        name: "True Resurrection".to_string(),
        level: 9,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Hours(1),
        range: SpellRange::Touch,
        components: Components::vsm("a sprinkle of holy water and diamonds worth at least 25,000 gp, which the spell consumes"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You touch a creature that has been dead for no longer than 200 years and that died for any reason except old age. If the creature's soul is free and willing, the creature is restored to life with all its hit points. This spell closes all wounds, neutralizes any poison, cures all diseases, and lifts any curses affecting the creature when it died. The spell replaces damaged or missing organs and limbs. The spell can even provide a new body if the original no longer exists.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Druid],
    });

    db.insert("wish".to_string(), SpellData {
        name: "Wish".to_string(),
        level: 9,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::v(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "Wish is the mightiest spell a mortal creature can cast. By simply speaking aloud, you can alter the very foundations of reality in accord with your desires. The basic use of this spell is to duplicate any other spell of 8th level or lower. You don't need to meet any requirements in that spell, including costly components. Alternatively, you can create one of a variety of powerful effects or wish for something else entirely.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("astral projection".to_string(), SpellData {
        name: "Astral Projection".to_string(),
        level: 9,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Hours(1),
        range: SpellRange::Feet(10),
        components: Components::vsm("for each creature you affect with this spell, you must provide one jacinth worth at least 1,000 gp and one ornately carved bar of silver worth at least 100 gp, all of which the spell consumes"),
        duration: SpellDuration::Special,
        concentration: false,
        ritual: false,
        description: "You and up to eight willing creatures within range project your astral bodies into the Astral Plane. The material body you leave behind is unconscious and in a state of suspended animation; it doesn't need food or air and doesn't age. Your astral body resembles your mortal form in almost every way, replicating your game statistics and possessions. The principal difference is the addition of a silvery cord that extends from between your shoulder blades and trails behind you. Your astral form can freely travel through the Astral Plane and can pass through portals there leading to any other plane.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("imprisonment".to_string(), SpellData {
        name: "Imprisonment".to_string(),
        level: 9,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Minutes(1),
        range: SpellRange::Feet(30),
        components: Components::vsm("a vellum depiction or a carved statuette in the likeness of the target, and a special component that varies according to the version of the spell you choose, worth at least 500 gp per Hit Die of the target"),
        duration: SpellDuration::UntilDispelled,
        concentration: false,
        ritual: false,
        description: "You create a magical restraint to hold a creature that you can see within range. The target must succeed on a Wisdom saving throw or be bound by the spell. On success, it is immune to this spell if you cast it again. While affected by this spell, the creature doesn't need to breathe, eat, or drink, and it doesn't age. Choose one of the following forms of imprisonment: Burial, Chaining, Hedged Prison, Minimus Containment, or Slumber. A dispel magic spell can end the spell only if it is cast as a 9th-level spell.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("not imprisoned".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("prismatic wall".to_string(), SpellData {
        name: "Prismatic Wall".to_string(),
        level: 9,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vs(),
        duration: SpellDuration::Minutes(10),
        concentration: false,
        ritual: false,
        description: "A shimmering, multicolored plane of light forms a vertical opaque wall up to 90 feet long, 30 feet high, and 1 inch thick, or a sphere up to 30 feet in diameter centered on a point you choose. The wall sheds bright light out to 100 feet and dim light for an additional 100 feet. You and creatures you designate can pass through and remain near the wall without harm. The wall consists of seven layers, each with a different color (red, orange, yellow, green, blue, indigo, violet). Each layer has a different effect and must be destroyed in order to reach the next layer.".to_string(),
        damage_dice: Some("10d6".to_string()),
        damage_type: Some(DamageType::Fire),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("varies by layer".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Wizard],
    });

    db.insert("shapechange".to_string(), SpellData {
        name: "Shapechange".to_string(),
        level: 9,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vsm("a jade circlet worth at least 1,500 gp, which you must place on your head before you cast the spell"),
        duration: SpellDuration::Hours(1),
        concentration: true,
        ritual: false,
        description: "You assume the form of a different creature for the duration. The new form can be of any creature with a challenge rating equal to your level or lower. The creature can't be a construct or an undead. You transform into an average example of that creature, one without any class levels or the Spellcasting trait. Your game statistics are replaced by the statistics of the chosen creature, though you retain your alignment and Intelligence, Wisdom, and Charisma scores. You also retain all of your skill and saving throw proficiencies. You can use an action to change form again.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Druid, SpellClass::Wizard],
    });

    db.insert("storm of vengeance".to_string(), SpellData {
        name: "Storm of Vengeance".to_string(),
        level: 9,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Sight,
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "A churning storm cloud forms, centered on a point you can see and spreading to a radius of 360 feet. Lightning flashes in the area, thunder booms, and strong winds roar. Each creature under the cloud when it appears must make a Constitution saving throw, taking 2d6 thunder damage on a failed save. Each round you maintain concentration, the storm produces different effects on your turn: Round 2 - acid rain (1d6 acid damage), Round 3 - lightning bolts (10d6 lightning damage, Dex save), Round 4 - hailstones (2d6 bludgeoning damage), Round 5-10 - wind and rain (ranged attacks disadvantage, flames extinguished).".to_string(),
        damage_dice: Some("2d6".to_string()),
        damage_type: Some(DamageType::Thunder),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("no thunder damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(360),
        classes: vec![SpellClass::Druid],
    });

    db.insert("time stop".to_string(), SpellData {
        name: "Time Stop".to_string(),
        level: 9,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::v(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You briefly stop the flow of time for everyone but yourself. No time passes for other creatures, while you take 1d4 + 1 turns in a row, during which you can use actions and move as normal. This spell ends if one of the actions you use during this period, or any effects that you create during this period, affects a creature other than you or an object being worn or carried by someone other than you. In addition, the spell ends if you move to a place more than 1,000 feet from the location where you cast it.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("weird".to_string(), SpellData {
        name: "Weird".to_string(),
        level: 9,
        school: SpellSchool::Illusion,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "Drawing on the deepest fears of a group of creatures, you create illusory creatures in their minds, visible only to them. Each creature in a 30-foot-radius sphere centered on a point of your choice within range must make a Wisdom saving throw. On a failed save, a creature becomes frightened for the duration. The illusion calls on the creature's deepest fears, manifesting its worst nightmares as an implacable threat. At the end of each of the frightened creature's turns, it must succeed on a Wisdom saving throw or take 4d10 psychic damage. On a successful save, the spell ends for that creature.".to_string(),
        damage_dice: Some("4d10".to_string()),
        damage_type: Some(DamageType::Psychic),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("not frightened".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(30),
        classes: vec![SpellClass::Warlock, SpellClass::Wizard],
    });
}
