//! 7th level spell definitions.

use super::types::*;
use crate::rules::DamageType;
use crate::world::Ability;
use std::collections::HashMap;

/// Register all 7th level spells into the spell database.
pub fn register_level7(db: &mut HashMap<String, SpellData>) {
    db.insert("delayed blast fireball".to_string(), SpellData {
        name: "Delayed Blast Fireball".to_string(),
        level: 7,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(150),
        components: Components::vsm("a tiny ball of bat guano and sulfur"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "A beam of yellow light flashes from your pointing finger, then condenses to linger at a chosen point within range as a glowing bead for the duration. When the spell ends, either because your concentration is broken or because you decide to end it, the bead blossoms with a low roar into an explosion of flame. Each creature in a 20-foot-radius sphere must make a Dexterity saving throw. A creature takes 12d6 fire damage on a failed save, or half on a success. The fire damage increases by 1d6 for each round the bead waited.".to_string(),
        damage_dice: Some("12d6".to_string()),
        damage_type: Some(DamageType::Fire),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d6".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(20),
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("finger of death".to_string(), SpellData {
        name: "Finger of Death".to_string(),
        level: 7,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You send negative energy coursing through a creature that you can see within range, causing it searing pain. The target must make a Constitution saving throw. It takes 7d8 + 30 necrotic damage on a failed save, or half as much damage on a successful one. A humanoid killed by this spell rises at the start of your next turn as a zombie that is permanently under your command.".to_string(),
        damage_dice: Some("7d8+30".to_string()),
        damage_type: Some(DamageType::Necrotic),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("fire storm".to_string(), SpellData {
        name: "Fire Storm".to_string(),
        level: 7,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(150),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "A storm made up of sheets of roaring flame appears in a location you choose within range. The area of the storm consists of up to ten 10-foot cubes, which you can arrange as you wish. Each creature in the area must make a Dexterity saving throw. It takes 7d10 fire damage on a failed save, or half as much damage on a successful one.".to_string(),
        damage_dice: Some("7d10".to_string()),
        damage_type: Some(DamageType::Fire),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Cube(10),
        classes: vec![SpellClass::Cleric, SpellClass::Druid, SpellClass::Sorcerer],
    });

    db.insert("plane shift".to_string(), SpellData {
        name: "Plane Shift".to_string(),
        level: 7,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("a forked, metal rod worth at least 250 gp, attuned to a particular plane of existence"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You and up to eight willing creatures who link hands in a circle are transported to a different plane of existence. You can specify a target destination in general terms. Alternatively, if you know the sigil sequence of a teleportation circle on another plane, you can specify that circle. You can use this spell to banish an unwilling creature to another plane with a melee spell attack and a Charisma save.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Charisma),
        save_effect: Some("not banished".to_string()),
        attack_type: Some(SpellAttackType::Melee),
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Druid, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("prismatic spray".to_string(), SpellData {
        name: "Prismatic Spray".to_string(),
        level: 7,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::SelfCone(60),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "Eight multicolored rays of light flash from your hand. Each ray is a different color and has a different power and purpose. Each creature in a 60-foot cone must make a Dexterity saving throw. For each target, roll a d8 to determine which color ray affects it: 1-Red (10d6 fire), 2-Orange (10d6 acid), 3-Yellow (10d6 lightning), 4-Green (10d6 poison), 5-Blue (10d6 cold), 6-Indigo (restrained then petrified), 7-Violet (blinded then banished), 8-Two rays.".to_string(),
        damage_dice: Some("10d6".to_string()),
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("half damage or resists effect".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Cone(60),
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("regenerate".to_string(), SpellData {
        name: "Regenerate".to_string(),
        level: 7,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Minutes(1),
        range: SpellRange::Touch,
        components: Components::vsm("a prayer wheel and holy water"),
        duration: SpellDuration::Hours(1),
        concentration: false,
        ritual: false,
        description: "You touch a creature and stimulate its natural healing ability. The target regains 4d8 + 15 hit points. For the duration of the spell, the target regains 1 hit point at the start of each of its turns (10 hit points each minute). The target's severed body members (fingers, legs, tails, and so on), if any, are restored after 2 minutes.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: Some("4d8+15".to_string()),
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Druid],
    });

    db.insert("resurrection".to_string(), SpellData {
        name: "Resurrection".to_string(),
        level: 7,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Hours(1),
        range: SpellRange::Touch,
        components: Components::vsm("a diamond worth at least 1,000 gp, which the spell consumes"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You touch a dead creature that has been dead for no more than a century, that didn't die of old age, and that isn't undead. If its soul is free and willing, the target returns to life with all its hit points. This spell neutralizes any poisons and cures normal diseases afflicting the creature when it died.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric],
    });

    db.insert("teleport".to_string(), SpellData {
        name: "Teleport".to_string(),
        level: 7,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(10),
        components: Components::v(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "This spell instantly transports you and up to eight willing creatures of your choice that you can see within range, or a single object that you can see within range, to a destination you select. If you target an object, it must be able to fit entirely inside a 10-foot cube. The destination must be known to you, and it must be on the same plane of existence as you.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("divine word".to_string(), SpellData {
        name: "Divine Word".to_string(),
        level: 7,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::BonusAction,
        range: SpellRange::Feet(30),
        components: Components::v(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You utter a divine word, imbued with the power that shaped the world at the dawn of creation. Each creature of your choice that you can see within range must make a Charisma saving throw. On a failed save, a creature suffers an effect based on its current hit points: 50 HP or less - deafened for 1 minute; 40 HP or less - deafened and blinded for 10 minutes; 30 HP or less - blinded, deafened, and stunned for 1 hour; 20 HP or less - killed instantly. Additionally, any celestial, elemental, fey, or fiend that fails its save is forced back to its plane of origin.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Charisma),
        save_effect: Some("no effect".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric],
    });

    db.insert("etherealness".to_string(), SpellData {
        name: "Etherealness".to_string(),
        level: 7,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vs(),
        duration: SpellDuration::Hours(8),
        concentration: false,
        ritual: false,
        description: "You step into the border regions of the Ethereal Plane, in the area where it overlaps with your current plane. You remain in the Border Ethereal for the duration or until you use your action to dismiss the spell. During this time, you can move in any direction. If you move up or down, every foot of movement costs an extra foot. You can see and hear the plane you originated from, but everything there looks gray, and you can't see anything more than 60 feet away. While on the Ethereal Plane, you can only affect and be affected by other creatures on that plane.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("forcecage".to_string(), SpellData {
        name: "Forcecage".to_string(),
        level: 7,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(100),
        components: Components::vsm("ruby dust worth 1,500 gp"),
        duration: SpellDuration::Hours(1),
        concentration: false,
        ritual: false,
        description: "An immobile, invisible, cube-shaped prison composed of magical force springs into existence around an area you choose within range. The prison can be a cage or a solid box, as you choose. A prison in the shape of a cage can be up to 20 feet on a side and is made from 1/2-inch diameter bars spaced 1/2 inch apart. A prison in the shape of a box can be up to 10 feet on a side, creating a solid barrier that prevents any matter from passing through it and blocking any spells cast into or out from the area. When you cast the spell, any creature that is completely inside the cage's area is trapped.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Charisma),
        save_effect: Some("teleports out".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Cube(20),
        classes: vec![SpellClass::Bard, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("mirage arcane".to_string(), SpellData {
        name: "Mirage Arcane".to_string(),
        level: 7,
        school: SpellSchool::Illusion,
        casting_time: CastingTime::Minutes(10),
        range: SpellRange::Sight,
        components: Components::vs(),
        duration: SpellDuration::Days(10),
        concentration: false,
        ritual: false,
        description: "You make terrain in an area up to 1 mile square look, sound, smell, and even feel like some other sort of terrain. The terrain's general shape remains the same, however. Open fields or a road could be made to resemble a swamp, hill, crevasse, or some other difficult or impassable terrain. A pond can be made to seem like a grassy meadow, a precipice like a gentle slope, or a rock-strewn gully like a wide and smooth road. Similarly, you can alter the appearance of structures, or add them where none are present. The illusion includes audible, visual, tactile, and olfactory elements, so it can turn clear ground into difficult terrain (or vice versa).".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Druid, SpellClass::Wizard],
    });

    db.insert("magnificent mansion".to_string(), SpellData {
        name: "Magnificent Mansion".to_string(),
        level: 7,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Minutes(1),
        range: SpellRange::Feet(300),
        components: Components::vsm("a miniature portal carved from ivory, a small piece of polished marble, and a tiny silver spoon, each item worth at least 5 gp"),
        duration: SpellDuration::Hours(24),
        concentration: false,
        ritual: false,
        description: "You conjure an extradimensional dwelling in range that lasts for the duration. You choose where its one entrance is located. The entrance shimmers faintly and is 5 feet wide and 10 feet tall. You and any creature you designate when you cast the spell can enter the extradimensional dwelling as long as the portal remains open. You can open or close the portal if you are within 30 feet of it. The dwelling is a magnificent foyer with numerous chambers beyond, with sufficient space for a lavish banquet, sleeping chambers, and unseen servants that attend all who enter.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Wizard],
    });

    db.insert("arcane sword".to_string(), SpellData {
        name: "Arcane Sword".to_string(),
        level: 7,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vsm("a miniature platinum sword with a grip and pommel of copper and zinc, worth 250 gp"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "You create a sword-shaped plane of force that hovers within range. It lasts for the duration. When the sword appears, you make a melee spell attack against a target of your choice within 5 feet of the sword. On a hit, the target takes 3d10 force damage. Until the spell ends, you can use a bonus action on each of your turns to move the sword up to 20 feet to a spot you can see and repeat this attack against the same target or a different one.".to_string(),
        damage_dice: Some("3d10".to_string()),
        damage_type: Some(DamageType::Force),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: Some(SpellAttackType::Melee),
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Wizard],
    });

    db.insert("project image".to_string(), SpellData {
        name: "Project Image".to_string(),
        level: 7,
        school: SpellSchool::Illusion,
        casting_time: CastingTime::Action,
        range: SpellRange::Miles(500),
        components: Components::vsm("a small replica of you made from materials worth at least 5 gp"),
        duration: SpellDuration::Days(1),
        concentration: true,
        ritual: false,
        description: "You create an illusory copy of yourself that lasts for the duration. The copy can appear at any location within range that you have seen before, regardless of intervening obstacles. The illusion looks and sounds like you but is intangible. If the illusion takes any damage, it disappears, and the spell ends. You can use your action to move this illusion up to twice your speed, and make it gesture, speak, and behave in whatever way you choose. It mimics your mannerisms perfectly. You can see through its eyes and hear through its ears as if you were in its space.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Wizard],
    });

    db.insert("reverse gravity".to_string(), SpellData {
        name: "Reverse Gravity".to_string(),
        level: 7,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(100),
        components: Components::vsm("a lodestone and iron filings"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "This spell reverses gravity in a 50-foot-radius, 100-foot high cylinder centered on a point within range. All creatures and objects that aren't somehow anchored to the ground in the area fall upward and reach the top of the area when you cast this spell. A creature can make a Dexterity saving throw to grab onto a fixed object it can reach, thus avoiding the fall. If some solid object (such as a ceiling) is encountered in this fall, falling objects and creatures strike it just as they would during a normal downward fall. When the spell ends, affected objects and creatures fall back down.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("grabs fixed object".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Cylinder(50, 100),
        classes: vec![SpellClass::Druid, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("sequester".to_string(), SpellData {
        name: "Sequester".to_string(),
        level: 7,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("a powder composed of diamond, emerald, ruby, and sapphire dust worth at least 5,000 gp, which the spell consumes"),
        duration: SpellDuration::UntilDispelled,
        concentration: false,
        ritual: false,
        description: "By means of this spell, a willing creature or an object can be hidden away, safe from detection for the duration. When you cast the spell and touch the target, it becomes invisible and can't be targeted by divination spells or perceived through scrying sensors. If the target is a creature, it falls into a state of suspended animation. Time ceases to flow for it, and it doesn't grow older. You can set a condition for the spell to end early.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Wizard],
    });

    db.insert("simulacrum".to_string(), SpellData {
        name: "Simulacrum".to_string(),
        level: 7,
        school: SpellSchool::Illusion,
        casting_time: CastingTime::Hours(12),
        range: SpellRange::Touch,
        components: Components::vsm("snow or ice in quantities sufficient to make a life-size copy of the duplicated creature; some hair, fingernail clippings, or other piece of that creature's body placed inside the snow or ice; and powdered ruby worth 1,500 gp, sprinkled over the duplicate and consumed by the spell"),
        duration: SpellDuration::UntilDispelled,
        concentration: false,
        ritual: false,
        description: "You shape an illusory duplicate of one beast or humanoid that is within range for the entire casting time of the spell. The duplicate is a creature, partially real and formed from ice or snow, and it can take actions and otherwise be affected as a normal creature. It appears to be the same as the original, but it has half the creature's hit point maximum and is formed without any equipment. Otherwise, the illusion uses all the statistics of the creature it duplicates. The simulacrum is friendly to you and creatures you designate. It obeys your spoken commands.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Wizard],
    });

    db.insert("symbol".to_string(), SpellData {
        name: "Symbol".to_string(),
        level: 7,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Minutes(1),
        range: SpellRange::Touch,
        components: Components::vsm("mercury, phosphorus, and powdered diamond and opal with a total value of at least 1,000 gp, which the spell consumes"),
        duration: SpellDuration::UntilDispelled,
        concentration: false,
        ritual: false,
        description: "When you cast this spell, you inscribe a harmful glyph either on a surface or within an object that can be closed to conceal the glyph. When triggered, the glyph erupts with magical energy in a 60-foot-radius sphere. Each creature in the area must make a saving throw based on the effect you choose: Death (10d10 necrotic, CON), Discord (bicker and argue, CON), Fear (frightened, WIS), Hopelessness (overwhelmed with despair, CHA), Insanity (irrational, INT), Pain (incapacitated, CON), Sleep (unconscious, WIS), or Stunning (stunned, WIS).".to_string(),
        damage_dice: Some("10d10".to_string()),
        damage_type: Some(DamageType::Necrotic),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("varies by effect".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(60),
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Wizard],
    });
}
