//! 1st level spell definitions.

use super::types::*;
use crate::rules::DamageType;
use crate::world::Ability;
use std::collections::HashMap;

/// Register all 1st level spells into the spell database.
pub fn register_level1(db: &mut HashMap<String, SpellData>) {
    db.insert("magic missile".to_string(), SpellData {
        name: "Magic Missile".to_string(),
        level: 1,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range. A dart deals 1d4+1 force damage. The darts all strike simultaneously. When cast with a higher level slot, create one additional dart per slot level above 1st.".to_string(),
        damage_dice: Some("3d4+3".to_string()), // 3 darts at 1d4+1 each
        damage_type: Some(DamageType::Force),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d4+1".to_string() },
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None, // Auto-hit
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("cure wounds".to_string(), SpellData {
        name: "Cure Wounds".to_string(),
        level: 1,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "A creature you touch regains hit points equal to 1d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs. When cast with a higher level slot, healing increases by 1d8 per slot level above 1st.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d8".to_string() },
        healing_dice: Some("1d8".to_string()),
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Druid, SpellClass::Paladin, SpellClass::Ranger],
    });

    db.insert("shield".to_string(), SpellData {
        name: "Shield".to_string(),
        level: 1,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Reaction("which you take when you are hit by an attack or targeted by magic missile".to_string()),
        range: SpellRange::Self_,
        components: Components::vs(),
        duration: SpellDuration::Rounds(1),
        concentration: false,
        ritual: false,
        description: "An invisible barrier of magical force appears and protects you. Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack, and you take no damage from magic missile.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("burning hands".to_string(), SpellData {
        name: "Burning Hands".to_string(),
        level: 1,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::SelfCone(15),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "As you hold your hands with thumbs touching and fingers spread, a thin sheet of flames shoots forth. Each creature in a 15-foot cone must make a Dexterity saving throw. A creature takes 3d6 fire damage on a failed save, or half as much on a successful one.".to_string(),
        damage_dice: Some("3d6".to_string()),
        damage_type: Some(DamageType::Fire),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d6".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Cone(15),
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("thunderwave".to_string(), SpellData {
        name: "Thunderwave".to_string(),
        level: 1,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::SelfRadius(15),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "A wave of thunderous force sweeps out from you. Each creature in a 15-foot cube originating from you must make a Constitution saving throw. On a failed save, a creature takes 2d8 thunder damage and is pushed 10 feet away. On a success, it takes half damage and isn't pushed.".to_string(),
        damage_dice: Some("2d8".to_string()),
        damage_type: Some(DamageType::Thunder),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d8".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("half damage, not pushed".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Cube(15),
        classes: vec![SpellClass::Bard, SpellClass::Druid, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("healing word".to_string(), SpellData {
        name: "Healing Word".to_string(),
        level: 1,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::BonusAction,
        range: SpellRange::Feet(60),
        components: Components::v(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "A creature of your choice that you can see within range regains hit points equal to 1d4 + your spellcasting ability modifier. This spell has no effect on undead or constructs.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d4".to_string() },
        healing_dice: Some("1d4".to_string()),
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Druid],
    });

    db.insert("guiding bolt".to_string(), SpellData {
        name: "Guiding Bolt".to_string(),
        level: 1,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vs(),
        duration: SpellDuration::Rounds(1),
        concentration: false,
        ritual: false,
        description: "A flash of light streaks toward a creature of your choice within range. Make a ranged spell attack. On a hit, the target takes 4d6 radiant damage, and the next attack roll made against this target before the end of your next turn has advantage.".to_string(),
        damage_dice: Some("4d6".to_string()),
        damage_type: Some(DamageType::Radiant),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d6".to_string() },
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: Some(SpellAttackType::Ranged),
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric],
    });

    db.insert("mage armor".to_string(), SpellData {
        name: "Mage Armor".to_string(),
        level: 1,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("a piece of cured leather"),
        duration: SpellDuration::Hours(8),
        concentration: false,
        ritual: false,
        description: "You touch a willing creature who isn't wearing armor, and a protective magical force surrounds it until the spell ends. The target's base AC becomes 13 + its Dexterity modifier. The spell ends if the target dons armor or if you dismiss the spell as an action.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("sleep".to_string(), SpellData {
        name: "Sleep".to_string(),
        level: 1,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(90),
        components: Components::vsm("a pinch of fine sand, rose petals, or a cricket"),
        duration: SpellDuration::Minutes(1),
        concentration: false,
        ritual: false,
        description: "This spell sends creatures into a magical slumber. Roll 5d8; the total is how many hit points of creatures this spell can affect. Starting with the creature with the lowest current HP, each creature falls unconscious until the spell ends, it takes damage, or someone uses an action to wake it.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "2d8".to_string() },
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(20),
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("hex".to_string(), SpellData {
        name: "Hex".to_string(),
        level: 1,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::BonusAction,
        range: SpellRange::Feet(90),
        components: Components::vsm("the petrified eye of a newt"),
        duration: SpellDuration::Hours(1),
        concentration: true,
        ritual: false,
        description: "You place a curse on a creature that you can see within range. Until the spell ends, you deal an extra 1d6 necrotic damage to the target whenever you hit it with an attack. Also, choose one ability when you cast the spell. The target has disadvantage on ability checks made with the chosen ability. If the target drops to 0 HP before this spell ends, you can use a bonus action on a subsequent turn to curse a new creature.".to_string(),
        damage_dice: Some("1d6".to_string()),
        damage_type: Some(DamageType::Necrotic),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Warlock],
    });

    db.insert("hellish rebuke".to_string(), SpellData {
        name: "Hellish Rebuke".to_string(),
        level: 1,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Reaction("which you take in response to being damaged by a creature within 60 feet of you that you can see".to_string()),
        range: SpellRange::Feet(60),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You point your finger, and the creature that damaged you is momentarily surrounded by hellish flames. The creature must make a Dexterity saving throw. It takes 2d10 fire damage on a failed save, or half as much damage on a successful one. When cast with a higher level slot, the damage increases by 1d10 per slot level above 1st.".to_string(),
        damage_dice: Some("2d10".to_string()),
        damage_type: Some(DamageType::Fire),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d10".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("half damage".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Warlock],
    });

    db.insert("armor of agathys".to_string(), SpellData {
        name: "Armor of Agathys".to_string(),
        level: 1,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vsm("a cup of water"),
        duration: SpellDuration::Hours(1),
        concentration: false,
        ritual: false,
        description: "A protective magical force surrounds you, manifesting as a spectral frost that covers you and your gear. You gain 5 temporary hit points for the duration. If a creature hits you with a melee attack while you have these hit points, the creature takes 5 cold damage. When cast with a higher level slot, both the temporary hit points and cold damage increase by 5 per slot level above 1st.".to_string(),
        damage_dice: Some("5".to_string()), // Flat damage, not dice
        damage_type: Some(DamageType::Cold),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "5".to_string() },
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Warlock],
    });

    db.insert("charm person".to_string(), SpellData {
        name: "Charm Person".to_string(),
        level: 1,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vs(),
        duration: SpellDuration::Hours(1),
        concentration: false,
        ritual: false,
        description: "You attempt to charm a humanoid you can see within range. It must make a Wisdom saving throw, with advantage if you or your companions are fighting it. If it fails, it is charmed by you until the spell ends or until you or your companions do anything harmful to it. The charmed creature regards you as a friendly acquaintance.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("not charmed".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Druid, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("alarm".to_string(), SpellData {
        name: "Alarm".to_string(),
        level: 1,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Minutes(1),
        range: SpellRange::Feet(30),
        components: Components::vsm("a tiny bell and a piece of fine silver wire"),
        duration: SpellDuration::Hours(8),
        concentration: false,
        ritual: true,
        description: "You set an alarm against unwanted intrusion. Choose a door, a window, or an area within range that is no larger than a 20-foot cube. Until the spell ends, an alarm alerts you whenever a Tiny or larger creature touches or enters the warded area. When you cast the spell, you can designate creatures that won't set off the alarm. You also choose whether the alarm is mental or audible.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Cube(20),
        classes: vec![SpellClass::Ranger, SpellClass::Wizard],
    });

    db.insert("animal friendship".to_string(), SpellData {
        name: "Animal Friendship".to_string(),
        level: 1,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vsm("a morsel of food"),
        duration: SpellDuration::Hours(24),
        concentration: false,
        ritual: false,
        description: "This spell lets you convince a beast that you mean it no harm. Choose a beast that you can see within range. It must see and hear you. If the beast's Intelligence is 4 or higher, the spell fails. Otherwise, the beast must succeed on a Wisdom saving throw or be charmed by you for the spell's duration.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("not charmed".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Druid, SpellClass::Ranger],
    });

    db.insert("bane".to_string(), SpellData {
        name: "Bane".to_string(),
        level: 1,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vsm("a drop of blood"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "Up to three creatures of your choice that you can see within range must make Charisma saving throws. Whenever a target that fails this saving throw makes an attack roll or a saving throw before the spell ends, the target must roll a d4 and subtract the number rolled from the attack roll or saving throw.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Charisma),
        save_effect: Some("not affected".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Cleric],
    });

    db.insert("bless".to_string(), SpellData {
        name: "Bless".to_string(),
        level: 1,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vsm("a sprinkling of holy water"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "You bless up to three creatures of your choice within range. Whenever a target makes an attack roll or a saving throw before the spell ends, the target can roll a d4 and add the number rolled to the attack roll or saving throw.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Paladin],
    });

    db.insert("chromatic orb".to_string(), SpellData {
        name: "Chromatic Orb".to_string(),
        level: 1,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(90),
        components: Components::vsm("a diamond worth at least 50 gp"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You hurl a 4-inch-diameter sphere of energy at a creature that you can see within range. You choose acid, cold, fire, lightning, poison, or thunder for the type of orb you create, and then make a ranged spell attack against the target. On a hit, the creature takes 3d8 damage of the type you chose.".to_string(),
        damage_dice: Some("3d8".to_string()),
        damage_type: None,
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d8".to_string() },
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: Some(SpellAttackType::Ranged),
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("command".to_string(), SpellData {
        name: "Command".to_string(),
        level: 1,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::v(),
        duration: SpellDuration::Rounds(1),
        concentration: false,
        ritual: false,
        description: "You speak a one-word command to a creature you can see within range. The target must succeed on a Wisdom saving throw or follow the command on its next turn. The spell has no effect if the target is undead, if it doesn't understand your language, or if your command is directly harmful to it. Common commands include Approach, Drop, Flee, Grovel, and Halt.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("not affected".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Paladin],
    });

    db.insert("comprehend languages".to_string(), SpellData {
        name: "Comprehend Languages".to_string(),
        level: 1,
        school: SpellSchool::Divination,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vsm("a pinch of soot and salt"),
        duration: SpellDuration::Hours(1),
        concentration: false,
        ritual: true,
        description: "For the duration, you understand the literal meaning of any spoken language that you hear. You also understand any written language that you see, but you must be touching the surface on which the words are written. It takes about 1 minute to read one page of text. This spell doesn't decode secret messages or glyphs that aren't part of a written language.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("create or destroy water".to_string(), SpellData {
        name: "Create or Destroy Water".to_string(),
        level: 1,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vsm("a drop of water if creating water or a few grains of sand if destroying it"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You either create or destroy water. Create Water: You create up to 10 gallons of clean water within range in an open container, or rain falls in a 30-foot cube within range. Destroy Water: You destroy up to 10 gallons of water in an open container, or destroy fog in a 30-foot cube within range.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Cube(30),
        classes: vec![SpellClass::Cleric, SpellClass::Druid],
    });

    db.insert("detect evil and good".to_string(), SpellData {
        name: "Detect Evil and Good".to_string(),
        level: 1,
        school: SpellSchool::Divination,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vs(),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "For the duration, you know if there is an aberration, celestial, elemental, fey, fiend, or undead within 30 feet of you, as well as where the creature is located. Similarly, you know if there is a place or object within 30 feet of you that has been magically consecrated or desecrated.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(30),
        classes: vec![SpellClass::Cleric, SpellClass::Paladin],
    });

    db.insert("detect magic".to_string(), SpellData {
        name: "Detect Magic".to_string(),
        level: 1,
        school: SpellSchool::Divination,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vs(),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: true,
        description: "For the duration, you sense the presence of magic within 30 feet of you. If you sense magic in this way, you can use your action to see a faint aura around any visible creature or object in the area that bears magic, and you learn its school of magic, if any. The spell can penetrate most barriers, but is blocked by 1 foot of stone, 1 inch of common metal, a thin sheet of lead, or 3 feet of wood or dirt.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(30),
        classes: vec![SpellClass::Bard, SpellClass::Cleric, SpellClass::Druid, SpellClass::Paladin, SpellClass::Ranger, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("detect poison and disease".to_string(), SpellData {
        name: "Detect Poison and Disease".to_string(),
        level: 1,
        school: SpellSchool::Divination,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vsm("a yew leaf"),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: true,
        description: "For the duration, you can sense the presence and location of poisons, poisonous creatures, and diseases within 30 feet of you. You also identify the kind of poison, poisonous creature, or disease in each case. The spell can penetrate most barriers, but is blocked by 1 foot of stone, 1 inch of common metal, a thin sheet of lead, or 3 feet of wood or dirt.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(30),
        classes: vec![SpellClass::Cleric, SpellClass::Druid, SpellClass::Paladin, SpellClass::Ranger],
    });

    db.insert("dissonant whispers".to_string(), SpellData {
        name: "Dissonant Whispers".to_string(),
        level: 1,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::v(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "You whisper a discordant melody that only one creature of your choice within range can hear, wracking it with terrible pain. The target must make a Wisdom saving throw. On a failed save, it takes 3d6 psychic damage and must immediately use its reaction, if available, to move as far as its speed allows away from you. On a successful save, the target takes half as much damage and doesn't have to move away.".to_string(),
        damage_dice: Some("3d6".to_string()),
        damage_type: Some(DamageType::Psychic),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d6".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("half damage, no forced movement".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard],
    });

    db.insert("divine favor".to_string(), SpellData {
        name: "Divine Favor".to_string(),
        level: 1,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::BonusAction,
        range: SpellRange::Self_,
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "Your prayer empowers you with divine radiance. Until the spell ends, your weapon attacks deal an extra 1d4 radiant damage on a hit.".to_string(),
        damage_dice: Some("1d4".to_string()),
        damage_type: Some(DamageType::Radiant),
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Paladin],
    });

    db.insert("entangle".to_string(), SpellData {
        name: "Entangle".to_string(),
        level: 1,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(90),
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "Grasping weeds and vines sprout from the ground in a 20-foot square starting from a point within range. For the duration, these plants turn the ground in the area into difficult terrain. A creature in the area when you cast the spell must succeed on a Strength saving throw or be restrained by the entangling plants until the spell ends. A restrained creature can use its action to make a Strength check against your spell save DC to free itself.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Strength),
        save_effect: Some("not restrained".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Cube(20),
        classes: vec![SpellClass::Druid],
    });

    db.insert("expeditious retreat".to_string(), SpellData {
        name: "Expeditious Retreat".to_string(),
        level: 1,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::BonusAction,
        range: SpellRange::Self_,
        components: Components::vs(),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "This spell allows you to move at an incredible pace. When you cast this spell, and then as a bonus action on each of your turns until the spell ends, you can take the Dash action.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("faerie fire".to_string(), SpellData {
        name: "Faerie Fire".to_string(),
        level: 1,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::v(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "Each object in a 20-foot cube within range is outlined in blue, green, or violet light (your choice). Any creature in the area when the spell is cast is also outlined in light if it fails a Dexterity saving throw. For the duration, objects and affected creatures shed dim light in a 10-foot radius. Any attack roll against an affected creature or object has advantage if the attacker can see it, and the affected creature or object can't benefit from being invisible.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Dexterity),
        save_effect: Some("not outlined".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::Cube(20),
        classes: vec![SpellClass::Bard, SpellClass::Druid],
    });

    db.insert("false life".to_string(), SpellData {
        name: "False Life".to_string(),
        level: 1,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vsm("a small amount of alcohol or distilled spirits"),
        duration: SpellDuration::Hours(1),
        concentration: false,
        ritual: false,
        description: "Bolstering yourself with a necromantic facsimile of life, you gain 1d4 + 4 temporary hit points for the duration. When cast with a higher level slot, you gain 5 additional temporary hit points for each slot level above 1st.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: Some("1d4+4".to_string()),
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("feather fall".to_string(), SpellData {
        name: "Feather Fall".to_string(),
        level: 1,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Reaction("which you take when you or a creature within 60 feet of you falls".to_string()),
        range: SpellRange::Feet(60),
        components: Components { verbal: true, somatic: false, material: Some("a small feather or piece of down".to_string()) },
        duration: SpellDuration::Minutes(1),
        concentration: false,
        ritual: false,
        description: "Choose up to five falling creatures within range. A falling creature's rate of descent slows to 60 feet per round until the spell ends. If the creature lands before the spell ends, it takes no falling damage and can land on its feet, and the spell ends for that creature.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("find familiar".to_string(), SpellData {
        name: "Find Familiar".to_string(),
        level: 1,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Hours(1),
        range: SpellRange::Feet(10),
        components: Components::vsm("10 gp worth of charcoal, incense, and herbs that must be consumed by fire in a brass brazier"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: true,
        description: "You gain the service of a familiar, a spirit that takes an animal form you choose: bat, cat, crab, frog, hawk, lizard, octopus, owl, poisonous snake, fish, rat, raven, sea horse, spider, or weasel. The familiar obeys your commands and can telepathically communicate with you within 100 feet. You can temporarily dismiss it, and as an action, you can see through its eyes and hear what it hears.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Wizard],
    });

    db.insert("fog cloud".to_string(), SpellData {
        name: "Fog Cloud".to_string(),
        level: 1,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(120),
        components: Components::vs(),
        duration: SpellDuration::Hours(1),
        concentration: true,
        ritual: false,
        description: "You create a 20-foot-radius sphere of fog centered on a point within range. The sphere spreads around corners, and its area is heavily obscured. It lasts for the duration or until a wind of moderate or greater speed (at least 10 miles per hour) disperses it. When cast with a higher level slot, the radius increases by 20 feet for each slot level above 1st.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(20),
        classes: vec![SpellClass::Druid, SpellClass::Ranger, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("goodberry".to_string(), SpellData {
        name: "Goodberry".to_string(),
        level: 1,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("a sprig of mistletoe"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "Up to ten berries appear in your hand and are infused with magic for the duration. A creature can use its action to eat one berry. Eating a berry restores 1 hit point, and the berry provides enough nourishment to sustain a creature for one day. The berries lose their potency if they have not been consumed within 24 hours of the casting of this spell.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: Some("1".to_string()),
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Druid, SpellClass::Ranger],
    });

    db.insert("heroism".to_string(), SpellData {
        name: "Heroism".to_string(),
        level: 1,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vs(),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "A willing creature you touch is imbued with bravery. Until the spell ends, the creature is immune to being frightened and gains temporary hit points equal to your spellcasting ability modifier at the start of each of its turns. When the spell ends, the target loses any remaining temporary hit points from this spell.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Paladin],
    });

    db.insert("hunter's mark".to_string(), SpellData {
        name: "Hunter's Mark".to_string(),
        level: 1,
        school: SpellSchool::Divination,
        casting_time: CastingTime::BonusAction,
        range: SpellRange::Feet(90),
        components: Components::v(),
        duration: SpellDuration::Hours(1),
        concentration: true,
        ritual: false,
        description: "You choose a creature you can see within range and mystically mark it as your quarry. Until the spell ends, you deal an extra 1d6 damage to the target whenever you hit it with a weapon attack, and you have advantage on any Wisdom (Perception) or Wisdom (Survival) check you make to find it. If the target drops to 0 hit points before this spell ends, you can use a bonus action on a subsequent turn to mark a new creature.".to_string(),
        damage_dice: Some("1d6".to_string()),
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Ranger],
    });

    db.insert("identify".to_string(), SpellData {
        name: "Identify".to_string(),
        level: 1,
        school: SpellSchool::Divination,
        casting_time: CastingTime::Minutes(1),
        range: SpellRange::Touch,
        components: Components::vsm("a pearl worth at least 100 gp and an owl feather"),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: true,
        description: "You choose one object that you must touch throughout the casting of the spell. If it is a magic item or some other magic-imbued object, you learn its properties and how to use them, whether it requires attunement to use, and how many charges it has, if any. You learn whether any spells are affecting the item and what they are. If the item was created by a spell, you learn which spell created it.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Wizard],
    });

    db.insert("inflict wounds".to_string(), SpellData {
        name: "Inflict Wounds".to_string(),
        level: 1,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "Make a melee spell attack against a creature you can reach. On a hit, the target takes 3d10 necrotic damage.".to_string(),
        damage_dice: Some("3d10".to_string()),
        damage_type: Some(DamageType::Necrotic),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d10".to_string() },
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: Some(SpellAttackType::Melee),
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric],
    });

    db.insert("jump".to_string(), SpellData {
        name: "Jump".to_string(),
        level: 1,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("a grasshopper's hind leg"),
        duration: SpellDuration::Minutes(1),
        concentration: false,
        ritual: false,
        description: "You touch a creature. The creature's jump distance is tripled until the spell ends.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Druid, SpellClass::Ranger, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("longstrider".to_string(), SpellData {
        name: "Longstrider".to_string(),
        level: 1,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("a pinch of dirt"),
        duration: SpellDuration::Hours(1),
        concentration: false,
        ritual: false,
        description: "You touch a creature. The target's speed increases by 10 feet until the spell ends. When cast with a higher level slot, you can target one additional creature for each slot level above 1st.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Druid, SpellClass::Ranger, SpellClass::Wizard],
    });

    db.insert("protection from evil and good".to_string(), SpellData {
        name: "Protection from Evil and Good".to_string(),
        level: 1,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Touch,
        components: Components::vsm("holy water or powdered silver and iron, which the spell consumes"),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "Until the spell ends, one willing creature you touch is protected against certain types of creatures: aberrations, celestials, elementals, fey, fiends, and undead. Creatures of those types have disadvantage on attack rolls against the target. The target also can't be charmed, frightened, or possessed by them. If the target is already affected, it has advantage on any new saving throw against the effect.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Paladin, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("purify food and drink".to_string(), SpellData {
        name: "Purify Food and Drink".to_string(),
        level: 1,
        school: SpellSchool::Transmutation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(10),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: true,
        description: "All nonmagical food and drink within a 5-foot-radius sphere centered on a point of your choice within range is purified and rendered free of poison and disease.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Sphere(5),
        classes: vec![SpellClass::Cleric, SpellClass::Druid, SpellClass::Paladin],
    });

    db.insert("ray of sickness".to_string(), SpellData {
        name: "Ray of Sickness".to_string(),
        level: 1,
        school: SpellSchool::Necromancy,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vs(),
        duration: SpellDuration::Instantaneous,
        concentration: false,
        ritual: false,
        description: "A ray of sickening greenish energy lashes out toward a creature within range. Make a ranged spell attack against the target. On a hit, the target takes 2d8 poison damage and must make a Constitution saving throw. On a failed save, it is also poisoned until the end of your next turn.".to_string(),
        damage_dice: Some("2d8".to_string()),
        damage_type: Some(DamageType::Poison),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d8".to_string() },
        healing_dice: None,
        save_type: Some(Ability::Constitution),
        save_effect: Some("not poisoned".to_string()),
        attack_type: Some(SpellAttackType::Ranged),
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("sanctuary".to_string(), SpellData {
        name: "Sanctuary".to_string(),
        level: 1,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::BonusAction,
        range: SpellRange::Feet(30),
        components: Components::vsm("a small silver mirror"),
        duration: SpellDuration::Minutes(1),
        concentration: false,
        ritual: false,
        description: "You ward a creature within range against attack. Until the spell ends, any creature who targets the warded creature with an attack or a harmful spell must first make a Wisdom saving throw. On a failed save, the creature must choose a new target or lose the attack or spell. This spell doesn't protect the warded creature from area effects. If the warded creature makes an attack, casts a spell that affects an enemy, or deals damage to another creature, this spell ends.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("can target warded creature".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric],
    });

    db.insert("shield of faith".to_string(), SpellData {
        name: "Shield of Faith".to_string(),
        level: 1,
        school: SpellSchool::Abjuration,
        casting_time: CastingTime::BonusAction,
        range: SpellRange::Feet(60),
        components: Components::vsm("a small parchment with a bit of holy text written on it"),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "A shimmering field appears and surrounds a creature of your choice within range, granting it a +2 bonus to AC for the duration.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Cleric, SpellClass::Paladin],
    });

    db.insert("silent image".to_string(), SpellData {
        name: "Silent Image".to_string(),
        level: 1,
        school: SpellSchool::Illusion,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vsm("a bit of fleece"),
        duration: SpellDuration::Minutes(10),
        concentration: true,
        ritual: false,
        description: "You create the image of an object, a creature, or some other visible phenomenon that is no larger than a 15-foot cube. The image appears at a spot within range and lasts for the duration. The image is purely visual; it isn't accompanied by sound, smell, or other sensory effects. You can use your action to cause the image to move to any spot within range. Physical interaction with the image reveals it to be an illusion.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::Cube(15),
        classes: vec![SpellClass::Bard, SpellClass::Sorcerer, SpellClass::Wizard],
    });

    db.insert("speak with animals".to_string(), SpellData {
        name: "Speak with Animals".to_string(),
        level: 1,
        school: SpellSchool::Divination,
        casting_time: CastingTime::Action,
        range: SpellRange::Self_,
        components: Components::vs(),
        duration: SpellDuration::Minutes(10),
        concentration: false,
        ritual: true,
        description: "You gain the ability to comprehend and verbally communicate with beasts for the duration. The knowledge and awareness of many beasts is limited by their intelligence, but at minimum, beasts can give you information about nearby locations and monsters, including whatever they can perceive or have perceived within the past day.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Druid, SpellClass::Ranger],
    });

    db.insert("tasha's hideous laughter".to_string(), SpellData {
        name: "Tasha's Hideous Laughter".to_string(),
        level: 1,
        school: SpellSchool::Enchantment,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vsm("tiny tarts and a feather that is waved in the air"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "A creature of your choice that you can see within range perceives everything as hilariously funny and falls into fits of laughter if this spell affects it. The target must succeed on a Wisdom saving throw or fall prone, becoming incapacitated and unable to stand up for the duration. A creature with an Intelligence score of 4 or less isn't affected. At the end of each of its turns, and each time it takes damage, the target can make another Wisdom saving throw.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: Some(Ability::Wisdom),
        save_effect: Some("not affected".to_string()),
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Wizard],
    });

    db.insert("unseen servant".to_string(), SpellData {
        name: "Unseen Servant".to_string(),
        level: 1,
        school: SpellSchool::Conjuration,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(60),
        components: Components::vsm("a piece of string and a bit of wood"),
        duration: SpellDuration::Hours(1),
        concentration: false,
        ritual: true,
        description: "This spell creates an invisible, mindless, shapeless, Medium force that performs simple tasks at your command until the spell ends. The servant springs into existence in an unoccupied space on the ground within range. It has AC 10, 1 hit point, and a Strength of 2, and it can't attack. It can perform simple tasks such as fetching things, cleaning, mending, folding clothes, lighting fires, serving food, and pouring wine.".to_string(),
        damage_dice: None,
        damage_type: None,
        damage_scaling: DamageScaling::None,
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: None,
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Bard, SpellClass::Warlock, SpellClass::Wizard],
    });

    db.insert("witch bolt".to_string(), SpellData {
        name: "Witch Bolt".to_string(),
        level: 1,
        school: SpellSchool::Evocation,
        casting_time: CastingTime::Action,
        range: SpellRange::Feet(30),
        components: Components::vsm("a twig from a tree that has been struck by lightning"),
        duration: SpellDuration::Minutes(1),
        concentration: true,
        ritual: false,
        description: "A beam of crackling, blue energy lances out toward a creature within range, forming a sustained arc of lightning between you and the target. Make a ranged spell attack against that creature. On a hit, the target takes 1d12 lightning damage, and on each of your turns for the duration, you can use your action to deal 1d12 lightning damage to the target automatically. The spell ends if you use your action to do anything else, if the target is ever outside the spell's range, or if the target has total cover from you.".to_string(),
        damage_dice: Some("1d12".to_string()),
        damage_type: Some(DamageType::Lightning),
        damage_scaling: DamageScaling::PerSlotLevel { extra_dice: "1d12".to_string() },
        healing_dice: None,
        save_type: None,
        save_effect: None,
        attack_type: Some(SpellAttackType::Ranged),
        area_of_effect: AreaOfEffect::None,
        classes: vec![SpellClass::Sorcerer, SpellClass::Warlock, SpellClass::Wizard],
    });
}
